# Project 2

Author: Cameron Mullaney

This is the second project for ST554.

DESCRIPTION AND NARRATIVE

# Part I

Part I is split up into two major tasks :
    A. The creation of my "Proj2Script.py" file
    B. The use of the SparkDataCheck class and the methods created within. 
    
Piece A is outlined thoroughly in the script file, and piece B is below.
I will be shwocasing the methods created in the script to analyze and validate data from a csv of air quality data.

Loading in the tools I'll need, as well as my "Proj2Script.py" file from piece A

In [4]:
import pandas as pd
import numpy as np
import math
from pyspark.sql import SparkSession
from Proj2Script import *

Setting up my spark session, and reading in the data!

In [7]:
spark = SparkSession.builder.appName('my_app').getOrCreate()

In [3]:
airdata = SparkDataCheck.fromcsv("air.csv", spark)
airdata.df.show()

+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+
|_c0|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+
|  0|3/10/2004|2026-03-23 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578|
|  1|3/10/2004|2026-03-23 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255|
|  2|3/10/2004|2026-03-23 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502|
|  3|3/10/2004|2026-03-23 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867|
|  4|3/10/2004|2026-03-23 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888|
|  5|3/10/2004|2026-03-23 23:00:00|   1.2|       1197|      38|     4.7|          750|     89|        1337|     96|        1393|        949|11.2|59.2|0.7848|
|  6|3/11/2004|2026-03-23 00:00:00|   1.2|       1185|      31|     3.6|          690|     62|        1462|     77|        1333|        733|11.3|56.8|0.7603|
|  7|3/11/2004|2026-03-23 01:00:00|   1.0|       1136|      31|     3.3|          672|     62|        1453|     76|        1333|        730|10.7|60.0|0.7702|
|  8|3/11/2004|2026-03-23 02:00:00|   0.9|       1094|      24|     2.3|          609|     45|        1579|     60|        1276|        620|10.7|59.7|0.7648|
|  9|3/11/2004|2026-03-23 03:00:00|   0.6|       1010|      19|     1.7|          561|   -200|        1705|   -200|        1235|        501|10.3|60.2|0.7517|
| 10|3/11/2004|2026-03-23 04:00:00|-200.0|       1011|      14|     1.3|          527|     21|        1818|     34|        1197|        445|10.1|60.5|0.7465|
| 11|3/11/2004|2026-03-23 05:00:00|   0.7|       1066|       8|     1.1|          512|     16|        1918|     28|        1182|        422|11.0|56.2|0.7366|
| 12|3/11/2004|2026-03-23 06:00:00|   0.7|       1052|      16|     1.6|          553|     34|        1738|     48|        1221|        472|10.5|58.1|0.7353|
| 13|3/11/2004|2026-03-23 07:00:00|   1.1|       1144|      29|     3.2|          667|     98|        1490|     82|        1339|        730|10.2|59.6|0.7417|
| 14|3/11/2004|2026-03-23 08:00:00|   2.0|       1333|      64|     8.0|          900|    174|        1136|    112|        1517|       1102|10.8|57.4|0.7408|
| 15|3/11/2004|2026-03-23 09:00:00|   2.2|       1351|      87|     9.5|          960|    129|        1079|    101|        1583|       1028|10.5|60.6|0.7691|
| 16|3/11/2004|2026-03-23 10:00:00|   1.7|       1233|      77|     6.3|          827|    112|        1218|     98|        1446|        860|10.8|58.4|0.7552|
| 17|3/11/2004|2026-03-23 11:00:00|   1.5|       1179|      43|     5.0|          762|     95|        1328|     92|        1362|        671|10.5|57.9|0.7352|
| 18|3/11/2004|2026-03-23 12:00:00|   1.6|       1236|      61|     5.2|          774|    104|        1301|     95|        1401|        664| 9.5|66.8|0.7951|
| 19|3/11/2004|2026-03-23 13:00:00|   1.9|       1286|      63|     7.3|          869|    146|        1162|    112|        1537|        799| 8.3|76.4|0.8393|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+
only showing top 20 rows

26/03/23 22:57:41 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
 Schema: _c0, Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
Expected: _c0 but found:
CSV file: file:///home/jupyter-cmullan@ncsu.edu/air.csv

### Initial Data Cleaning

There seem to be a couple issues here: 
1. I'm noticing this data has some -200 values in it, which correspond to missing values - Let's replace those with NULL values. \
I've designed the Proj2Script to properly handle NULL values, so this should ensure our methods work properly.
2. Python isn't happy with the header format. Let's rename some columns for clarity. We can get rid of the first column which is serving as a secondary index.
This is code pulled from our first project, and updated to match the current data processing method.
3. Our "Time" column seems to have assigned today's date to the times. We'll remove that.

In [4]:
airdata.df =  airdata.df.withColumnRenamed("C6H6(GT)", "B")\
                        .withColumnRenamed("PT08.S1(CO)", "CO")\
                        .withColumnRenamed("PT08.S2(NMHC)", "NMHC")\
                        .withColumnRenamed("PT08.S3(NOx)", "NOx")\
                        .withColumnRenamed("PT08.S4(NO2)", "NO2")\
                        .withColumnRenamed("PT08.S5(O3)", "O3")

airdata.df = airdata.df.drop("_c0")

Here, we're replacing those -200 values with NULL.

In [5]:
airdata.df = airdata.df.replace(float(-200), None) ## Replace "-200" with "NaN"

In [6]:
airdata.df.show()

+---------+-------------------+------+----+--------+----+----+-------+----+-------+----+----+----+----+------+
|     Date|               Time|CO(GT)|  CO|NMHC(GT)|   B|NMHC|NOx(GT)| NOx|NO2(GT)| NO2|  O3|   T|  RH|    AH|
+---------+-------------------+------+----+--------+----+----+-------+----+-------+----+----+----+----+------+
|3/10/2004|2026-03-23 18:00:00|   2.6|1360|     150|11.9|1046|    166|1056|    113|1692|1268|13.6|48.9|0.7578|
|3/10/2004|2026-03-23 19:00:00|   2.0|1292|     112| 9.4| 955|    103|1174|     92|1559| 972|13.3|47.7|0.7255|
|3/10/2004|2026-03-23 20:00:00|   2.2|1402|      88| 9.0| 939|    131|1140|    114|1555|1074|11.9|54.0|0.7502|
|3/10/2004|2026-03-23 21:00:00|   2.2|1376|      80| 9.2| 948|    172|1092|    122|1584|1203|11.0|60.0|0.7867|
|3/10/2004|2026-03-23 22:00:00|   1.6|1272|      51| 6.5| 836|    131|1205|    116|1490|1110|11.2|59.6|0.7888|
|3/10/2004|2026-03-23 23:00:00|   1.2|1197|      38| 4.7| 750|     89|1337|     96|1393| 949|11.2|59.2|0.7848|
|3/11/2004|2026-03-23 00:00:00|   1.2|1185|      31| 3.6| 690|     62|1462|     77|1333| 733|11.3|56.8|0.7603|
|3/11/2004|2026-03-23 01:00:00|   1.0|1136|      31| 3.3| 672|     62|1453|     76|1333| 730|10.7|60.0|0.7702|
|3/11/2004|2026-03-23 02:00:00|   0.9|1094|      24| 2.3| 609|     45|1579|     60|1276| 620|10.7|59.7|0.7648|
|3/11/2004|2026-03-23 03:00:00|   0.6|1010|      19| 1.7| 561|   NULL|1705|   NULL|1235| 501|10.3|60.2|0.7517|
|3/11/2004|2026-03-23 04:00:00|  NULL|1011|      14| 1.3| 527|     21|1818|     34|1197| 445|10.1|60.5|0.7465|
|3/11/2004|2026-03-23 05:00:00|   0.7|1066|       8| 1.1| 512|     16|1918|     28|1182| 422|11.0|56.2|0.7366|
|3/11/2004|2026-03-23 06:00:00|   0.7|1052|      16| 1.6| 553|     34|1738|     48|1221| 472|10.5|58.1|0.7353|
|3/11/2004|2026-03-23 07:00:00|   1.1|1144|      29| 3.2| 667|     98|1490|     82|1339| 730|10.2|59.6|0.7417|
|3/11/2004|2026-03-23 08:00:00|   2.0|1333|      64| 8.0| 900|    174|1136|    112|1517|1102|10.8|57.4|0.7408|
|3/11/2004|2026-03-23 09:00:00|   2.2|1351|      87| 9.5| 960|    129|1079|    101|1583|1028|10.5|60.6|0.7691|
|3/11/2004|2026-03-23 10:00:00|   1.7|1233|      77| 6.3| 827|    112|1218|     98|1446| 860|10.8|58.4|0.7552|
|3/11/2004|2026-03-23 11:00:00|   1.5|1179|      43| 5.0| 762|     95|1328|     92|1362| 671|10.5|57.9|0.7352|
|3/11/2004|2026-03-23 12:00:00|   1.6|1236|      61| 5.2| 774|    104|1301|     95|1401| 664| 9.5|66.8|0.7951|
|3/11/2004|2026-03-23 13:00:00|   1.9|1286|      63| 7.3| 869|    146|1162|    112|1537| 799| 8.3|76.4|0.8393|
+---------+-------------------+------+----+--------+----+----+-------+----+-------+----+----+----+----+------+
only showing top 20 rows

In [7]:
airdata.df.show()

+---------+-------------------+------+----+--------+----+----+-------+----+-------+----+----+----+----+------+
|     Date|               Time|CO(GT)|  CO|NMHC(GT)|   B|NMHC|NOx(GT)| NOx|NO2(GT)| NO2|  O3|   T|  RH|    AH|
+---------+-------------------+------+----+--------+----+----+-------+----+-------+----+----+----+----+------+
|3/10/2004|2026-03-23 18:00:00|   2.6|1360|     150|11.9|1046|    166|1056|    113|1692|1268|13.6|48.9|0.7578|
|3/10/2004|2026-03-23 19:00:00|   2.0|1292|     112| 9.4| 955|    103|1174|     92|1559| 972|13.3|47.7|0.7255|
|3/10/2004|2026-03-23 20:00:00|   2.2|1402|      88| 9.0| 939|    131|1140|    114|1555|1074|11.9|54.0|0.7502|
|3/10/2004|2026-03-23 21:00:00|   2.2|1376|      80| 9.2| 948|    172|1092|    122|1584|1203|11.0|60.0|0.7867|
|3/10/2004|2026-03-23 22:00:00|   1.6|1272|      51| 6.5| 836|    131|1205|    116|1490|1110|11.2|59.6|0.7888|
|3/10/2004|2026-03-23 23:00:00|   1.2|1197|      38| 4.7| 750|     89|1337|     96|1393| 949|11.2|59.2|0.7848|
|3/11/2004|2026-03-23 00:00:00|   1.2|1185|      31| 3.6| 690|     62|1462|     77|1333| 733|11.3|56.8|0.7603|
|3/11/2004|2026-03-23 01:00:00|   1.0|1136|      31| 3.3| 672|     62|1453|     76|1333| 730|10.7|60.0|0.7702|
|3/11/2004|2026-03-23 02:00:00|   0.9|1094|      24| 2.3| 609|     45|1579|     60|1276| 620|10.7|59.7|0.7648|
|3/11/2004|2026-03-23 03:00:00|   0.6|1010|      19| 1.7| 561|   NULL|1705|   NULL|1235| 501|10.3|60.2|0.7517|
|3/11/2004|2026-03-23 04:00:00|  NULL|1011|      14| 1.3| 527|     21|1818|     34|1197| 445|10.1|60.5|0.7465|
|3/11/2004|2026-03-23 05:00:00|   0.7|1066|       8| 1.1| 512|     16|1918|     28|1182| 422|11.0|56.2|0.7366|
|3/11/2004|2026-03-23 06:00:00|   0.7|1052|      16| 1.6| 553|     34|1738|     48|1221| 472|10.5|58.1|0.7353|
|3/11/2004|2026-03-23 07:00:00|   1.1|1144|      29| 3.2| 667|     98|1490|     82|1339| 730|10.2|59.6|0.7417|
|3/11/2004|2026-03-23 08:00:00|   2.0|1333|      64| 8.0| 900|    174|1136|    112|1517|1102|10.8|57.4|0.7408|
|3/11/2004|2026-03-23 09:00:00|   2.2|1351|      87| 9.5| 960|    129|1079|    101|1583|1028|10.5|60.6|0.7691|
|3/11/2004|2026-03-23 10:00:00|   1.7|1233|      77| 6.3| 827|    112|1218|     98|1446| 860|10.8|58.4|0.7552|
|3/11/2004|2026-03-23 11:00:00|   1.5|1179|      43| 5.0| 762|     95|1328|     92|1362| 671|10.5|57.9|0.7352|
|3/11/2004|2026-03-23 12:00:00|   1.6|1236|      61| 5.2| 774|    104|1301|     95|1401| 664| 9.5|66.8|0.7951|
|3/11/2004|2026-03-23 13:00:00|   1.9|1286|      63| 7.3| 869|    146|1162|    112|1537| 799| 8.3|76.4|0.8393|
+---------+-------------------+------+----+--------+----+----+-------+----+-------+----+----+----+----+------+
only showing top 20 rows

Great! Looks like our values have been replaced! To be sure, let's run minmax.

In [8]:
airdata.minmax()

<class 'NoneType'>
Column Provided: False
Grouping Var Provided: False

                       0
min(CO(GT))       0.1000
max(CO(GT))      11.9000
min(CO)         647.0000
max(CO)        2040.0000
min(NMHC(GT))     7.0000
max(NMHC(GT))  1189.0000
min(B)            0.1000
max(B)           63.7000
min(NMHC)       383.0000
max(NMHC)      2214.0000
min(NOx(GT))      2.0000
max(NOx(GT))   1479.0000
min(NOx)        322.0000
max(NOx)       2683.0000
min(NO2(GT))      2.0000
max(NO2(GT))    340.0000
min(NO2)        551.0000
max(NO2)       2775.0000
min(O3)         221.0000
max(O3)        2523.0000
min(T)           -1.9000
max(T)           44.6000
min(RH)           9.2000
max(RH)          88.7000
min(AH)           0.1847
max(AH)           2.2310

Perfect! No -200 values to be seen!

Now, for the Time column:

In [9]:
airdata.df = airdata.df.withColumn("Time", F.date_format(F.col("Time"), "HH:mm:ss"))

In [10]:
airdata.df.show()

+---------+--------+------+----+--------+----+----+-------+----+-------+----+----+----+----+------+
|     Date|    Time|CO(GT)|  CO|NMHC(GT)|   B|NMHC|NOx(GT)| NOx|NO2(GT)| NO2|  O3|   T|  RH|    AH|
+---------+--------+------+----+--------+----+----+-------+----+-------+----+----+----+----+------+
|3/10/2004|18:00:00|   2.6|1360|     150|11.9|1046|    166|1056|    113|1692|1268|13.6|48.9|0.7578|
|3/10/2004|19:00:00|   2.0|1292|     112| 9.4| 955|    103|1174|     92|1559| 972|13.3|47.7|0.7255|
|3/10/2004|20:00:00|   2.2|1402|      88| 9.0| 939|    131|1140|    114|1555|1074|11.9|54.0|0.7502|
|3/10/2004|21:00:00|   2.2|1376|      80| 9.2| 948|    172|1092|    122|1584|1203|11.0|60.0|0.7867|
|3/10/2004|22:00:00|   1.6|1272|      51| 6.5| 836|    131|1205|    116|1490|1110|11.2|59.6|0.7888|
|3/10/2004|23:00:00|   1.2|1197|      38| 4.7| 750|     89|1337|     96|1393| 949|11.2|59.2|0.7848|
|3/11/2004|00:00:00|   1.2|1185|      31| 3.6| 690|     62|1462|     77|1333| 733|11.3|56.8|0.7603|
|3/11/2004|01:00:00|   1.0|1136|      31| 3.3| 672|     62|1453|     76|1333| 730|10.7|60.0|0.7702|
|3/11/2004|02:00:00|   0.9|1094|      24| 2.3| 609|     45|1579|     60|1276| 620|10.7|59.7|0.7648|
|3/11/2004|03:00:00|   0.6|1010|      19| 1.7| 561|   NULL|1705|   NULL|1235| 501|10.3|60.2|0.7517|
|3/11/2004|04:00:00|  NULL|1011|      14| 1.3| 527|     21|1818|     34|1197| 445|10.1|60.5|0.7465|
|3/11/2004|05:00:00|   0.7|1066|       8| 1.1| 512|     16|1918|     28|1182| 422|11.0|56.2|0.7366|
|3/11/2004|06:00:00|   0.7|1052|      16| 1.6| 553|     34|1738|     48|1221| 472|10.5|58.1|0.7353|
|3/11/2004|07:00:00|   1.1|1144|      29| 3.2| 667|     98|1490|     82|1339| 730|10.2|59.6|0.7417|
|3/11/2004|08:00:00|   2.0|1333|      64| 8.0| 900|    174|1136|    112|1517|1102|10.8|57.4|0.7408|
|3/11/2004|09:00:00|   2.2|1351|      87| 9.5| 960|    129|1079|    101|1583|1028|10.5|60.6|0.7691|
|3/11/2004|10:00:00|   1.7|1233|      77| 6.3| 827|    112|1218|     98|1446| 860|10.8|58.4|0.7552|
|3/11/2004|11:00:00|   1.5|1179|      43| 5.0| 762|     95|1328|     92|1362| 671|10.5|57.9|0.7352|
|3/11/2004|12:00:00|   1.6|1236|      61| 5.2| 774|    104|1301|     95|1401| 664| 9.5|66.8|0.7951|
|3/11/2004|13:00:00|   1.9|1286|      63| 7.3| 869|    146|1162|    112|1537| 799| 8.3|76.4|0.8393|
+---------+--------+------+----+--------+----+----+-------+----+-------+----+----+----+----+------+
only showing top 20 rows

Great! Now we have a date, and a time column. \
Finally, I am going to make a list of our column names for use later.

In [11]:
OGcols = airdata.df.columns
OGcols

['Date',
 'Time',
 'CO(GT)',
 'CO',
 'NMHC(GT)',
 'B',
 'NMHC',
 'NOx(GT)',
 'NOx',
 'NO2(GT)',
 'NO2',
 'O3',
 'T',
 'RH',
 'AH']

## Method Testing

Here, I give some examples of the methods I've written, to show that they work.
I will provide 4-5 examples for each.

### Validation Methods

#### withinlimits()

This method takes in an item of SparkDataCheck class, a specific column name from that item's df attribute, and an upper and lower numeric bound. \
Then, a new column is appended providing True or False values for each row in the specified column, depending on if it's in the specified range. \
Only one bound is required, and if only one is provided a one-sided check will be made.
This method returns the edited SparkDataCheck item, so .show() must be used to see the table.

##### Numeric column specified, upper and lower bound supplied:

Here, you can see a new column on the right, corresponding to if each value of T is within the specified 10-11 range. \
This column is added to the SparkDataCheck item in use.

In [12]:
airdata.withinlimits("T", lower = 10, upper = 11).df.show()

+---------+--------+------+----+--------+----+----+-------+----+-------+----+----+----+----+------+----------------+
|     Date|    Time|CO(GT)|  CO|NMHC(GT)|   B|NMHC|NOx(GT)| NOx|NO2(GT)| NO2|  O3|   T|  RH|    AH|T within (10,11)|
+---------+--------+------+----+--------+----+----+-------+----+-------+----+----+----+----+------+----------------+
|3/10/2004|18:00:00|   2.6|1360|     150|11.9|1046|    166|1056|    113|1692|1268|13.6|48.9|0.7578|           false|
|3/10/2004|19:00:00|   2.0|1292|     112| 9.4| 955|    103|1174|     92|1559| 972|13.3|47.7|0.7255|           false|
|3/10/2004|20:00:00|   2.2|1402|      88| 9.0| 939|    131|1140|    114|1555|1074|11.9|54.0|0.7502|           false|
|3/10/2004|21:00:00|   2.2|1376|      80| 9.2| 948|    172|1092|    122|1584|1203|11.0|60.0|0.7867|            true|
|3/10/2004|22:00:00|   1.6|1272|      51| 6.5| 836|    131|1205|    116|1490|1110|11.2|59.6|0.7888|           false|
|3/10/2004|23:00:00|   1.2|1197|      38| 4.7| 750|     89|1337|     96|1393| 949|11.2|59.2|0.7848|           false|
|3/11/2004|00:00:00|   1.2|1185|      31| 3.6| 690|     62|1462|     77|1333| 733|11.3|56.8|0.7603|           false|
|3/11/2004|01:00:00|   1.0|1136|      31| 3.3| 672|     62|1453|     76|1333| 730|10.7|60.0|0.7702|            true|
|3/11/2004|02:00:00|   0.9|1094|      24| 2.3| 609|     45|1579|     60|1276| 620|10.7|59.7|0.7648|            true|
|3/11/2004|03:00:00|   0.6|1010|      19| 1.7| 561|   NULL|1705|   NULL|1235| 501|10.3|60.2|0.7517|            true|
|3/11/2004|04:00:00|  NULL|1011|      14| 1.3| 527|     21|1818|     34|1197| 445|10.1|60.5|0.7465|            true|
|3/11/2004|05:00:00|   0.7|1066|       8| 1.1| 512|     16|1918|     28|1182| 422|11.0|56.2|0.7366|            true|
|3/11/2004|06:00:00|   0.7|1052|      16| 1.6| 553|     34|1738|     48|1221| 472|10.5|58.1|0.7353|            true|
|3/11/2004|07:00:00|   1.1|1144|      29| 3.2| 667|     98|1490|     82|1339| 730|10.2|59.6|0.7417|            true|
|3/11/2004|08:00:00|   2.0|1333|      64| 8.0| 900|    174|1136|    112|1517|1102|10.8|57.4|0.7408|            true|
|3/11/2004|09:00:00|   2.2|1351|      87| 9.5| 960|    129|1079|    101|1583|1028|10.5|60.6|0.7691|            true|
|3/11/2004|10:00:00|   1.7|1233|      77| 6.3| 827|    112|1218|     98|1446| 860|10.8|58.4|0.7552|            true|
|3/11/2004|11:00:00|   1.5|1179|      43| 5.0| 762|     95|1328|     92|1362| 671|10.5|57.9|0.7352|            true|
|3/11/2004|12:00:00|   1.6|1236|      61| 5.2| 774|    104|1301|     95|1401| 664| 9.5|66.8|0.7951|           false|
|3/11/2004|13:00:00|   1.9|1286|      63| 7.3| 869|    146|1162|    112|1537| 799| 8.3|76.4|0.8393|           false|
+---------+--------+------+----+--------+----+----+-------+----+-------+----+----+----+----+------+----------------+
only showing top 20 rows

##### Numeric column specified, only lower bound supplied:

Here, you can see a new column on the right, corresponding to if each value of T is below the given value 1.5. \
This column is added to the SparkDataCheck item in use.

In [13]:
airdata.withinlimits("CO(GT)", lower = 1.5).df.show()

+---------+--------+------+----+--------+----+----+-------+----+-------+----+----+----+----+------+----------------+----------------+
|     Date|    Time|CO(GT)|  CO|NMHC(GT)|   B|NMHC|NOx(GT)| NOx|NO2(GT)| NO2|  O3|   T|  RH|    AH|T within (10,11)|CO(GT) above 1.5|
+---------+--------+------+----+--------+----+----+-------+----+-------+----+----+----+----+------+----------------+----------------+
|3/10/2004|18:00:00|   2.6|1360|     150|11.9|1046|    166|1056|    113|1692|1268|13.6|48.9|0.7578|           false|            true|
|3/10/2004|19:00:00|   2.0|1292|     112| 9.4| 955|    103|1174|     92|1559| 972|13.3|47.7|0.7255|           false|            true|
|3/10/2004|20:00:00|   2.2|1402|      88| 9.0| 939|    131|1140|    114|1555|1074|11.9|54.0|0.7502|           false|            true|
|3/10/2004|21:00:00|   2.2|1376|      80| 9.2| 948|    172|1092|    122|1584|1203|11.0|60.0|0.7867|            true|            true|
|3/10/2004|22:00:00|   1.6|1272|      51| 6.5| 836|    131|1205|    116|1490|1110|11.2|59.6|0.7888|           false|            true|
|3/10/2004|23:00:00|   1.2|1197|      38| 4.7| 750|     89|1337|     96|1393| 949|11.2|59.2|0.7848|           false|           false|
|3/11/2004|00:00:00|   1.2|1185|      31| 3.6| 690|     62|1462|     77|1333| 733|11.3|56.8|0.7603|           false|           false|
|3/11/2004|01:00:00|   1.0|1136|      31| 3.3| 672|     62|1453|     76|1333| 730|10.7|60.0|0.7702|            true|           false|
|3/11/2004|02:00:00|   0.9|1094|      24| 2.3| 609|     45|1579|     60|1276| 620|10.7|59.7|0.7648|            true|           false|
|3/11/2004|03:00:00|   0.6|1010|      19| 1.7| 561|   NULL|1705|   NULL|1235| 501|10.3|60.2|0.7517|            true|           false|
|3/11/2004|04:00:00|  NULL|1011|      14| 1.3| 527|     21|1818|     34|1197| 445|10.1|60.5|0.7465|            true|            NULL|
|3/11/2004|05:00:00|   0.7|1066|       8| 1.1| 512|     16|1918|     28|1182| 422|11.0|56.2|0.7366|            true|           false|
|3/11/2004|06:00:00|   0.7|1052|      16| 1.6| 553|     34|1738|     48|1221| 472|10.5|58.1|0.7353|            true|           false|
|3/11/2004|07:00:00|   1.1|1144|      29| 3.2| 667|     98|1490|     82|1339| 730|10.2|59.6|0.7417|            true|           false|
|3/11/2004|08:00:00|   2.0|1333|      64| 8.0| 900|    174|1136|    112|1517|1102|10.8|57.4|0.7408|            true|            true|
|3/11/2004|09:00:00|   2.2|1351|      87| 9.5| 960|    129|1079|    101|1583|1028|10.5|60.6|0.7691|            true|            true|
|3/11/2004|10:00:00|   1.7|1233|      77| 6.3| 827|    112|1218|     98|1446| 860|10.8|58.4|0.7552|            true|            true|
|3/11/2004|11:00:00|   1.5|1179|      43| 5.0| 762|     95|1328|     92|1362| 671|10.5|57.9|0.7352|            true|            true|
|3/11/2004|12:00:00|   1.6|1236|      61| 5.2| 774|    104|1301|     95|1401| 664| 9.5|66.8|0.7951|           false|            true|
|3/11/2004|13:00:00|   1.9|1286|      63| 7.3| 869|    146|1162|    112|1537| 799| 8.3|76.4|0.8393|           false|            true|
+---------+--------+------+----+--------+----+----+-------+----+-------+----+----+----+----+------+----------------+----------------+
only showing top 20 rows

##### Non-numeric column specified, lower bound supplied:

When a non-numeric column is specified, the method makes no changes and returns your object unedited. A message is printed, telling you what's wrong.

In [14]:
airdata.withinlimits("T within (10,11)", lower = 50).df.show()

Non-numeric column supplied - No actions taken
+---------+--------+------+----+--------+----+----+-------+----+-------+----+----+----+----+------+----------------+----------------+
|     Date|    Time|CO(GT)|  CO|NMHC(GT)|   B|NMHC|NOx(GT)| NOx|NO2(GT)| NO2|  O3|   T|  RH|    AH|T within (10,11)|CO(GT) above 1.5|
+---------+--------+------+----+--------+----+----+-------+----+-------+----+----+----+----+------+----------------+----------------+
|3/10/2004|18:00:00|   2.6|1360|     150|11.9|1046|    166|1056|    113|1692|1268|13.6|48.9|0.7578|           false|            true|
|3/10/2004|19:00:00|   2.0|1292|     112| 9.4| 955|    103|1174|     92|1559| 972|13.3|47.7|0.7255|           false|            true|
|3/10/2004|20:00:00|   2.2|1402|      88| 9.0| 939|    131|1140|    114|1555|1074|11.9|54.0|0.7502|           false|            true|
|3/10/2004|21:00:00|   2.2|1376|      80| 9.2| 948|    172|1092|    122|1584|1203|11.0|60.0|0.7867|            true|            true|
|3/10/2004|22:00:00|   1.6|1272|      51| 6.5| 836|    131|1205|    116|1490|1110|11.2|59.6|0.7888|           false|            true|
|3/10/2004|23:00:00|   1.2|1197|      38| 4.7| 750|     89|1337|     96|1393| 949|11.2|59.2|0.7848|           false|           false|
|3/11/2004|00:00:00|   1.2|1185|      31| 3.6| 690|     62|1462|     77|1333| 733|11.3|56.8|0.7603|           false|           false|
|3/11/2004|01:00:00|   1.0|1136|      31| 3.3| 672|     62|1453|     76|1333| 730|10.7|60.0|0.7702|            true|           false|
|3/11/2004|02:00:00|   0.9|1094|      24| 2.3| 609|     45|1579|     60|1276| 620|10.7|59.7|0.7648|            true|           false|
|3/11/2004|03:00:00|   0.6|1010|      19| 1.7| 561|   NULL|1705|   NULL|1235| 501|10.3|60.2|0.7517|            true|           false|
|3/11/2004|04:00:00|  NULL|1011|      14| 1.3| 527|     21|1818|     34|1197| 445|10.1|60.5|0.7465|            true|            NULL|
|3/11/2004|05:00:00|   0.7|1066|       8| 1.1| 512|     16|1918|     28|1182| 422|11.0|56.2|0.7366|            true|           false|
|3/11/2004|06:00:00|   0.7|1052|      16| 1.6| 553|     34|1738|     48|1221| 472|10.5|58.1|0.7353|            true|           false|
|3/11/2004|07:00:00|   1.1|1144|      29| 3.2| 667|     98|1490|     82|1339| 730|10.2|59.6|0.7417|            true|           false|
|3/11/2004|08:00:00|   2.0|1333|      64| 8.0| 900|    174|1136|    112|1517|1102|10.8|57.4|0.7408|            true|            true|
|3/11/2004|09:00:00|   2.2|1351|      87| 9.5| 960|    129|1079|    101|1583|1028|10.5|60.6|0.7691|            true|            true|
|3/11/2004|10:00:00|   1.7|1233|      77| 6.3| 827|    112|1218|     98|1446| 860|10.8|58.4|0.7552|            true|            true|
|3/11/2004|11:00:00|   1.5|1179|      43| 5.0| 762|     95|1328|     92|1362| 671|10.5|57.9|0.7352|            true|            true|
|3/11/2004|12:00:00|   1.6|1236|      61| 5.2| 774|    104|1301|     95|1401| 664| 9.5|66.8|0.7951|           false|            true|
|3/11/2004|13:00:00|   1.9|1286|      63| 7.3| 869|    146|1162|    112|1537| 799| 8.3|76.4|0.8393|           false|            true|
+---------+--------+------+----+--------+----+----+-------+----+-------+----+----+----+----+------+----------------+----------------+
only showing top 20 rows

##### Numeric column specified, only upper bound given:

This is similar to the earlier example with CO(GT). With only an upper bound given, every value <= 1200 is True, while all others are False.

In [15]:
airdata.withinlimits("CO", upper = 1200).df.show()

+---------+--------+------+----+--------+----+----+-------+----+-------+----+----+----+----+------+----------------+----------------+-------------+
|     Date|    Time|CO(GT)|  CO|NMHC(GT)|   B|NMHC|NOx(GT)| NOx|NO2(GT)| NO2|  O3|   T|  RH|    AH|T within (10,11)|CO(GT) above 1.5|CO below 1200|
+---------+--------+------+----+--------+----+----+-------+----+-------+----+----+----+----+------+----------------+----------------+-------------+
|3/10/2004|18:00:00|   2.6|1360|     150|11.9|1046|    166|1056|    113|1692|1268|13.6|48.9|0.7578|           false|            true|        false|
|3/10/2004|19:00:00|   2.0|1292|     112| 9.4| 955|    103|1174|     92|1559| 972|13.3|47.7|0.7255|           false|            true|        false|
|3/10/2004|20:00:00|   2.2|1402|      88| 9.0| 939|    131|1140|    114|1555|1074|11.9|54.0|0.7502|           false|            true|        false|
|3/10/2004|21:00:00|   2.2|1376|      80| 9.2| 948|    172|1092|    122|1584|1203|11.0|60.0|0.7867|            true|            true|        false|
|3/10/2004|22:00:00|   1.6|1272|      51| 6.5| 836|    131|1205|    116|1490|1110|11.2|59.6|0.7888|           false|            true|        false|
|3/10/2004|23:00:00|   1.2|1197|      38| 4.7| 750|     89|1337|     96|1393| 949|11.2|59.2|0.7848|           false|           false|         true|
|3/11/2004|00:00:00|   1.2|1185|      31| 3.6| 690|     62|1462|     77|1333| 733|11.3|56.8|0.7603|           false|           false|         true|
|3/11/2004|01:00:00|   1.0|1136|      31| 3.3| 672|     62|1453|     76|1333| 730|10.7|60.0|0.7702|            true|           false|         true|
|3/11/2004|02:00:00|   0.9|1094|      24| 2.3| 609|     45|1579|     60|1276| 620|10.7|59.7|0.7648|            true|           false|         true|
|3/11/2004|03:00:00|   0.6|1010|      19| 1.7| 561|   NULL|1705|   NULL|1235| 501|10.3|60.2|0.7517|            true|           false|         true|
|3/11/2004|04:00:00|  NULL|1011|      14| 1.3| 527|     21|1818|     34|1197| 445|10.1|60.5|0.7465|            true|            NULL|         true|
|3/11/2004|05:00:00|   0.7|1066|       8| 1.1| 512|     16|1918|     28|1182| 422|11.0|56.2|0.7366|            true|           false|         true|
|3/11/2004|06:00:00|   0.7|1052|      16| 1.6| 553|     34|1738|     48|1221| 472|10.5|58.1|0.7353|            true|           false|         true|
|3/11/2004|07:00:00|   1.1|1144|      29| 3.2| 667|     98|1490|     82|1339| 730|10.2|59.6|0.7417|            true|           false|         true|
|3/11/2004|08:00:00|   2.0|1333|      64| 8.0| 900|    174|1136|    112|1517|1102|10.8|57.4|0.7408|            true|            true|        false|
|3/11/2004|09:00:00|   2.2|1351|      87| 9.5| 960|    129|1079|    101|1583|1028|10.5|60.6|0.7691|            true|            true|        false|
|3/11/2004|10:00:00|   1.7|1233|      77| 6.3| 827|    112|1218|     98|1446| 860|10.8|58.4|0.7552|            true|            true|        false|
|3/11/2004|11:00:00|   1.5|1179|      43| 5.0| 762|     95|1328|     92|1362| 671|10.5|57.9|0.7352|            true|            true|         true|
|3/11/2004|12:00:00|   1.6|1236|      61| 5.2| 774|    104|1301|     95|1401| 664| 9.5|66.8|0.7951|           false|            true|        false|
|3/11/2004|13:00:00|   1.9|1286|      63| 7.3| 869|    146|1162|    112|1537| 799| 8.3|76.4|0.8393|           false|            true|        false|
+---------+--------+------+----+--------+----+----+-------+----+-------+----+----+----+----+------+----------------+----------------+-------------+
only showing top 20 rows

Just for ease of viewing, I will remove these additional columns now.

In [16]:
airdata.df = airdata.df.select(OGcols)
airdata.df.show()

+---------+--------+------+----+--------+----+----+-------+----+-------+----+----+----+----+------+
|     Date|    Time|CO(GT)|  CO|NMHC(GT)|   B|NMHC|NOx(GT)| NOx|NO2(GT)| NO2|  O3|   T|  RH|    AH|
+---------+--------+------+----+--------+----+----+-------+----+-------+----+----+----+----+------+
|3/10/2004|18:00:00|   2.6|1360|     150|11.9|1046|    166|1056|    113|1692|1268|13.6|48.9|0.7578|
|3/10/2004|19:00:00|   2.0|1292|     112| 9.4| 955|    103|1174|     92|1559| 972|13.3|47.7|0.7255|
|3/10/2004|20:00:00|   2.2|1402|      88| 9.0| 939|    131|1140|    114|1555|1074|11.9|54.0|0.7502|
|3/10/2004|21:00:00|   2.2|1376|      80| 9.2| 948|    172|1092|    122|1584|1203|11.0|60.0|0.7867|
|3/10/2004|22:00:00|   1.6|1272|      51| 6.5| 836|    131|1205|    116|1490|1110|11.2|59.6|0.7888|
|3/10/2004|23:00:00|   1.2|1197|      38| 4.7| 750|     89|1337|     96|1393| 949|11.2|59.2|0.7848|
|3/11/2004|00:00:00|   1.2|1185|      31| 3.6| 690|     62|1462|     77|1333| 733|11.3|56.8|0.7603|
|3/11/2004|01:00:00|   1.0|1136|      31| 3.3| 672|     62|1453|     76|1333| 730|10.7|60.0|0.7702|
|3/11/2004|02:00:00|   0.9|1094|      24| 2.3| 609|     45|1579|     60|1276| 620|10.7|59.7|0.7648|
|3/11/2004|03:00:00|   0.6|1010|      19| 1.7| 561|   NULL|1705|   NULL|1235| 501|10.3|60.2|0.7517|
|3/11/2004|04:00:00|  NULL|1011|      14| 1.3| 527|     21|1818|     34|1197| 445|10.1|60.5|0.7465|
|3/11/2004|05:00:00|   0.7|1066|       8| 1.1| 512|     16|1918|     28|1182| 422|11.0|56.2|0.7366|
|3/11/2004|06:00:00|   0.7|1052|      16| 1.6| 553|     34|1738|     48|1221| 472|10.5|58.1|0.7353|
|3/11/2004|07:00:00|   1.1|1144|      29| 3.2| 667|     98|1490|     82|1339| 730|10.2|59.6|0.7417|
|3/11/2004|08:00:00|   2.0|1333|      64| 8.0| 900|    174|1136|    112|1517|1102|10.8|57.4|0.7408|
|3/11/2004|09:00:00|   2.2|1351|      87| 9.5| 960|    129|1079|    101|1583|1028|10.5|60.6|0.7691|
|3/11/2004|10:00:00|   1.7|1233|      77| 6.3| 827|    112|1218|     98|1446| 860|10.8|58.4|0.7552|
|3/11/2004|11:00:00|   1.5|1179|      43| 5.0| 762|     95|1328|     92|1362| 671|10.5|57.9|0.7352|
|3/11/2004|12:00:00|   1.6|1236|      61| 5.2| 774|    104|1301|     95|1401| 664| 9.5|66.8|0.7951|
|3/11/2004|13:00:00|   1.9|1286|      63| 7.3| 869|    146|1162|    112|1537| 799| 8.3|76.4|0.8393|
+---------+--------+------+----+--------+----+----+-------+----+-------+----+----+----+----+------+
only showing top 20 rows

#### onlist()

This method takes in an item of SparkDataCheck class, a specific column name from that item's df attribute, and a list of strings. \
Then, a new column is appended providing True or False values for each row in the specified column, depending on if that value is on the list. \
This method returns the edited SparkDataCheck item, so .show() must be used to see the table.

##### String column supplied, string supplied:

Here, you can see a new column on the right, corresponding to if each cell in "Date" is 3/10/2004. \
This column is added to the SparkDataCheck item in use.

In [17]:
airdata.onlist("Date", ["3/10/2004"]).df.show()

+---------+--------+------+----+--------+----+----+-------+----+-------+----+----+----+----+------+------------+
|     Date|    Time|CO(GT)|  CO|NMHC(GT)|   B|NMHC|NOx(GT)| NOx|NO2(GT)| NO2|  O3|   T|  RH|    AH|Date on list|
+---------+--------+------+----+--------+----+----+-------+----+-------+----+----+----+----+------+------------+
|3/10/2004|18:00:00|   2.6|1360|     150|11.9|1046|    166|1056|    113|1692|1268|13.6|48.9|0.7578|        true|
|3/10/2004|19:00:00|   2.0|1292|     112| 9.4| 955|    103|1174|     92|1559| 972|13.3|47.7|0.7255|        true|
|3/10/2004|20:00:00|   2.2|1402|      88| 9.0| 939|    131|1140|    114|1555|1074|11.9|54.0|0.7502|        true|
|3/10/2004|21:00:00|   2.2|1376|      80| 9.2| 948|    172|1092|    122|1584|1203|11.0|60.0|0.7867|        true|
|3/10/2004|22:00:00|   1.6|1272|      51| 6.5| 836|    131|1205|    116|1490|1110|11.2|59.6|0.7888|        true|
|3/10/2004|23:00:00|   1.2|1197|      38| 4.7| 750|     89|1337|     96|1393| 949|11.2|59.2|0.7848|        true|
|3/11/2004|00:00:00|   1.2|1185|      31| 3.6| 690|     62|1462|     77|1333| 733|11.3|56.8|0.7603|       false|
|3/11/2004|01:00:00|   1.0|1136|      31| 3.3| 672|     62|1453|     76|1333| 730|10.7|60.0|0.7702|       false|
|3/11/2004|02:00:00|   0.9|1094|      24| 2.3| 609|     45|1579|     60|1276| 620|10.7|59.7|0.7648|       false|
|3/11/2004|03:00:00|   0.6|1010|      19| 1.7| 561|   NULL|1705|   NULL|1235| 501|10.3|60.2|0.7517|       false|
|3/11/2004|04:00:00|  NULL|1011|      14| 1.3| 527|     21|1818|     34|1197| 445|10.1|60.5|0.7465|       false|
|3/11/2004|05:00:00|   0.7|1066|       8| 1.1| 512|     16|1918|     28|1182| 422|11.0|56.2|0.7366|       false|
|3/11/2004|06:00:00|   0.7|1052|      16| 1.6| 553|     34|1738|     48|1221| 472|10.5|58.1|0.7353|       false|
|3/11/2004|07:00:00|   1.1|1144|      29| 3.2| 667|     98|1490|     82|1339| 730|10.2|59.6|0.7417|       false|
|3/11/2004|08:00:00|   2.0|1333|      64| 8.0| 900|    174|1136|    112|1517|1102|10.8|57.4|0.7408|       false|
|3/11/2004|09:00:00|   2.2|1351|      87| 9.5| 960|    129|1079|    101|1583|1028|10.5|60.6|0.7691|       false|
|3/11/2004|10:00:00|   1.7|1233|      77| 6.3| 827|    112|1218|     98|1446| 860|10.8|58.4|0.7552|       false|
|3/11/2004|11:00:00|   1.5|1179|      43| 5.0| 762|     95|1328|     92|1362| 671|10.5|57.9|0.7352|       false|
|3/11/2004|12:00:00|   1.6|1236|      61| 5.2| 774|    104|1301|     95|1401| 664| 9.5|66.8|0.7951|       false|
|3/11/2004|13:00:00|   1.9|1286|      63| 7.3| 869|    146|1162|    112|1537| 799| 8.3|76.4|0.8393|       false|
+---------+--------+------+----+--------+----+----+-------+----+-------+----+----+----+----+------+------------+
only showing top 20 rows

##### String column supplied, list of strings supplied:

Here, you can see a new column on the right, corresponding to if each cell in "Time" is in the list we provided.

In [18]:
airdata.onlist("Time", ["19:00:00", "21:00:00", "09:00:00"]).df.show()

+---------+--------+------+----+--------+----+----+-------+----+-------+----+----+----+----+------+------------+------------+
|     Date|    Time|CO(GT)|  CO|NMHC(GT)|   B|NMHC|NOx(GT)| NOx|NO2(GT)| NO2|  O3|   T|  RH|    AH|Date on list|Time on list|
+---------+--------+------+----+--------+----+----+-------+----+-------+----+----+----+----+------+------------+------------+
|3/10/2004|18:00:00|   2.6|1360|     150|11.9|1046|    166|1056|    113|1692|1268|13.6|48.9|0.7578|        true|       false|
|3/10/2004|19:00:00|   2.0|1292|     112| 9.4| 955|    103|1174|     92|1559| 972|13.3|47.7|0.7255|        true|        true|
|3/10/2004|20:00:00|   2.2|1402|      88| 9.0| 939|    131|1140|    114|1555|1074|11.9|54.0|0.7502|        true|       false|
|3/10/2004|21:00:00|   2.2|1376|      80| 9.2| 948|    172|1092|    122|1584|1203|11.0|60.0|0.7867|        true|        true|
|3/10/2004|22:00:00|   1.6|1272|      51| 6.5| 836|    131|1205|    116|1490|1110|11.2|59.6|0.7888|        true|       false|
|3/10/2004|23:00:00|   1.2|1197|      38| 4.7| 750|     89|1337|     96|1393| 949|11.2|59.2|0.7848|        true|       false|
|3/11/2004|00:00:00|   1.2|1185|      31| 3.6| 690|     62|1462|     77|1333| 733|11.3|56.8|0.7603|       false|       false|
|3/11/2004|01:00:00|   1.0|1136|      31| 3.3| 672|     62|1453|     76|1333| 730|10.7|60.0|0.7702|       false|       false|
|3/11/2004|02:00:00|   0.9|1094|      24| 2.3| 609|     45|1579|     60|1276| 620|10.7|59.7|0.7648|       false|       false|
|3/11/2004|03:00:00|   0.6|1010|      19| 1.7| 561|   NULL|1705|   NULL|1235| 501|10.3|60.2|0.7517|       false|       false|
|3/11/2004|04:00:00|  NULL|1011|      14| 1.3| 527|     21|1818|     34|1197| 445|10.1|60.5|0.7465|       false|       false|
|3/11/2004|05:00:00|   0.7|1066|       8| 1.1| 512|     16|1918|     28|1182| 422|11.0|56.2|0.7366|       false|       false|
|3/11/2004|06:00:00|   0.7|1052|      16| 1.6| 553|     34|1738|     48|1221| 472|10.5|58.1|0.7353|       false|       false|
|3/11/2004|07:00:00|   1.1|1144|      29| 3.2| 667|     98|1490|     82|1339| 730|10.2|59.6|0.7417|       false|       false|
|3/11/2004|08:00:00|   2.0|1333|      64| 8.0| 900|    174|1136|    112|1517|1102|10.8|57.4|0.7408|       false|       false|
|3/11/2004|09:00:00|   2.2|1351|      87| 9.5| 960|    129|1079|    101|1583|1028|10.5|60.6|0.7691|       false|        true|
|3/11/2004|10:00:00|   1.7|1233|      77| 6.3| 827|    112|1218|     98|1446| 860|10.8|58.4|0.7552|       false|       false|
|3/11/2004|11:00:00|   1.5|1179|      43| 5.0| 762|     95|1328|     92|1362| 671|10.5|57.9|0.7352|       false|       false|
|3/11/2004|12:00:00|   1.6|1236|      61| 5.2| 774|    104|1301|     95|1401| 664| 9.5|66.8|0.7951|       false|       false|
|3/11/2004|13:00:00|   1.9|1286|      63| 7.3| 869|    146|1162|    112|1537| 799| 8.3|76.4|0.8393|       false|       false|
+---------+--------+------+----+--------+----+----+-------+----+-------+----+----+----+----+------+------------+------------+
only showing top 20 rows

##### String column specified, non-numeric list supplied:

In this case, the method will determine that the list contains non-strings, print the issue, and return the unedited object.

In [19]:
airdata.onlist("Time", [18,19,20]).df.show()

Non-string list supplied - No actions taken
+---------+--------+------+----+--------+----+----+-------+----+-------+----+----+----+----+------+------------+------------+
|     Date|    Time|CO(GT)|  CO|NMHC(GT)|   B|NMHC|NOx(GT)| NOx|NO2(GT)| NO2|  O3|   T|  RH|    AH|Date on list|Time on list|
+---------+--------+------+----+--------+----+----+-------+----+-------+----+----+----+----+------+------------+------------+
|3/10/2004|18:00:00|   2.6|1360|     150|11.9|1046|    166|1056|    113|1692|1268|13.6|48.9|0.7578|        true|       false|
|3/10/2004|19:00:00|   2.0|1292|     112| 9.4| 955|    103|1174|     92|1559| 972|13.3|47.7|0.7255|        true|        true|
|3/10/2004|20:00:00|   2.2|1402|      88| 9.0| 939|    131|1140|    114|1555|1074|11.9|54.0|0.7502|        true|       false|
|3/10/2004|21:00:00|   2.2|1376|      80| 9.2| 948|    172|1092|    122|1584|1203|11.0|60.0|0.7867|        true|        true|
|3/10/2004|22:00:00|   1.6|1272|      51| 6.5| 836|    131|1205|    116|1490|1110|11.2|59.6|0.7888|        true|       false|
|3/10/2004|23:00:00|   1.2|1197|      38| 4.7| 750|     89|1337|     96|1393| 949|11.2|59.2|0.7848|        true|       false|
|3/11/2004|00:00:00|   1.2|1185|      31| 3.6| 690|     62|1462|     77|1333| 733|11.3|56.8|0.7603|       false|       false|
|3/11/2004|01:00:00|   1.0|1136|      31| 3.3| 672|     62|1453|     76|1333| 730|10.7|60.0|0.7702|       false|       false|
|3/11/2004|02:00:00|   0.9|1094|      24| 2.3| 609|     45|1579|     60|1276| 620|10.7|59.7|0.7648|       false|       false|
|3/11/2004|03:00:00|   0.6|1010|      19| 1.7| 561|   NULL|1705|   NULL|1235| 501|10.3|60.2|0.7517|       false|       false|
|3/11/2004|04:00:00|  NULL|1011|      14| 1.3| 527|     21|1818|     34|1197| 445|10.1|60.5|0.7465|       false|       false|
|3/11/2004|05:00:00|   0.7|1066|       8| 1.1| 512|     16|1918|     28|1182| 422|11.0|56.2|0.7366|       false|       false|
|3/11/2004|06:00:00|   0.7|1052|      16| 1.6| 553|     34|1738|     48|1221| 472|10.5|58.1|0.7353|       false|       false|
|3/11/2004|07:00:00|   1.1|1144|      29| 3.2| 667|     98|1490|     82|1339| 730|10.2|59.6|0.7417|       false|       false|
|3/11/2004|08:00:00|   2.0|1333|      64| 8.0| 900|    174|1136|    112|1517|1102|10.8|57.4|0.7408|       false|       false|
|3/11/2004|09:00:00|   2.2|1351|      87| 9.5| 960|    129|1079|    101|1583|1028|10.5|60.6|0.7691|       false|        true|
|3/11/2004|10:00:00|   1.7|1233|      77| 6.3| 827|    112|1218|     98|1446| 860|10.8|58.4|0.7552|       false|       false|
|3/11/2004|11:00:00|   1.5|1179|      43| 5.0| 762|     95|1328|     92|1362| 671|10.5|57.9|0.7352|       false|       false|
|3/11/2004|12:00:00|   1.6|1236|      61| 5.2| 774|    104|1301|     95|1401| 664| 9.5|66.8|0.7951|       false|       false|
|3/11/2004|13:00:00|   1.9|1286|      63| 7.3| 869|    146|1162|    112|1537| 799| 8.3|76.4|0.8393|       false|       false|
+---------+--------+------+----+--------+----+----+-------+----+-------+----+----+----+----+------+------------+------------+
only showing top 20 rows

##### Non-string column specified, valid list given:

In this case, it will return the unedited object and print the issue.

In [20]:
airdata.onlist("B", ["11.9", "4.7"]).df.show()

Non-string column supplied - No actions taken
+---------+--------+------+----+--------+----+----+-------+----+-------+----+----+----+----+------+------------+------------+
|     Date|    Time|CO(GT)|  CO|NMHC(GT)|   B|NMHC|NOx(GT)| NOx|NO2(GT)| NO2|  O3|   T|  RH|    AH|Date on list|Time on list|
+---------+--------+------+----+--------+----+----+-------+----+-------+----+----+----+----+------+------------+------------+
|3/10/2004|18:00:00|   2.6|1360|     150|11.9|1046|    166|1056|    113|1692|1268|13.6|48.9|0.7578|        true|       false|
|3/10/2004|19:00:00|   2.0|1292|     112| 9.4| 955|    103|1174|     92|1559| 972|13.3|47.7|0.7255|        true|        true|
|3/10/2004|20:00:00|   2.2|1402|      88| 9.0| 939|    131|1140|    114|1555|1074|11.9|54.0|0.7502|        true|       false|
|3/10/2004|21:00:00|   2.2|1376|      80| 9.2| 948|    172|1092|    122|1584|1203|11.0|60.0|0.7867|        true|        true|
|3/10/2004|22:00:00|   1.6|1272|      51| 6.5| 836|    131|1205|    116|1490|1110|11.2|59.6|0.7888|        true|       false|
|3/10/2004|23:00:00|   1.2|1197|      38| 4.7| 750|     89|1337|     96|1393| 949|11.2|59.2|0.7848|        true|       false|
|3/11/2004|00:00:00|   1.2|1185|      31| 3.6| 690|     62|1462|     77|1333| 733|11.3|56.8|0.7603|       false|       false|
|3/11/2004|01:00:00|   1.0|1136|      31| 3.3| 672|     62|1453|     76|1333| 730|10.7|60.0|0.7702|       false|       false|
|3/11/2004|02:00:00|   0.9|1094|      24| 2.3| 609|     45|1579|     60|1276| 620|10.7|59.7|0.7648|       false|       false|
|3/11/2004|03:00:00|   0.6|1010|      19| 1.7| 561|   NULL|1705|   NULL|1235| 501|10.3|60.2|0.7517|       false|       false|
|3/11/2004|04:00:00|  NULL|1011|      14| 1.3| 527|     21|1818|     34|1197| 445|10.1|60.5|0.7465|       false|       false|
|3/11/2004|05:00:00|   0.7|1066|       8| 1.1| 512|     16|1918|     28|1182| 422|11.0|56.2|0.7366|       false|       false|
|3/11/2004|06:00:00|   0.7|1052|      16| 1.6| 553|     34|1738|     48|1221| 472|10.5|58.1|0.7353|       false|       false|
|3/11/2004|07:00:00|   1.1|1144|      29| 3.2| 667|     98|1490|     82|1339| 730|10.2|59.6|0.7417|       false|       false|
|3/11/2004|08:00:00|   2.0|1333|      64| 8.0| 900|    174|1136|    112|1517|1102|10.8|57.4|0.7408|       false|       false|
|3/11/2004|09:00:00|   2.2|1351|      87| 9.5| 960|    129|1079|    101|1583|1028|10.5|60.6|0.7691|       false|        true|
|3/11/2004|10:00:00|   1.7|1233|      77| 6.3| 827|    112|1218|     98|1446| 860|10.8|58.4|0.7552|       false|       false|
|3/11/2004|11:00:00|   1.5|1179|      43| 5.0| 762|     95|1328|     92|1362| 671|10.5|57.9|0.7352|       false|       false|
|3/11/2004|12:00:00|   1.6|1236|      61| 5.2| 774|    104|1301|     95|1401| 664| 9.5|66.8|0.7951|       false|       false|
|3/11/2004|13:00:00|   1.9|1286|      63| 7.3| 869|    146|1162|    112|1537| 799| 8.3|76.4|0.8393|       false|       false|
+---------+--------+------+----+--------+----+----+-------+----+-------+----+----+----+----+------+------------+------------+
only showing top 20 rows

##### Once again, clearing the new columns

In [21]:
airdata.df = airdata.df.select(OGcols)
airdata.df.show()

+---------+--------+------+----+--------+----+----+-------+----+-------+----+----+----+----+------+
|     Date|    Time|CO(GT)|  CO|NMHC(GT)|   B|NMHC|NOx(GT)| NOx|NO2(GT)| NO2|  O3|   T|  RH|    AH|
+---------+--------+------+----+--------+----+----+-------+----+-------+----+----+----+----+------+
|3/10/2004|18:00:00|   2.6|1360|     150|11.9|1046|    166|1056|    113|1692|1268|13.6|48.9|0.7578|
|3/10/2004|19:00:00|   2.0|1292|     112| 9.4| 955|    103|1174|     92|1559| 972|13.3|47.7|0.7255|
|3/10/2004|20:00:00|   2.2|1402|      88| 9.0| 939|    131|1140|    114|1555|1074|11.9|54.0|0.7502|
|3/10/2004|21:00:00|   2.2|1376|      80| 9.2| 948|    172|1092|    122|1584|1203|11.0|60.0|0.7867|
|3/10/2004|22:00:00|   1.6|1272|      51| 6.5| 836|    131|1205|    116|1490|1110|11.2|59.6|0.7888|
|3/10/2004|23:00:00|   1.2|1197|      38| 4.7| 750|     89|1337|     96|1393| 949|11.2|59.2|0.7848|
|3/11/2004|00:00:00|   1.2|1185|      31| 3.6| 690|     62|1462|     77|1333| 733|11.3|56.8|0.7603|
|3/11/2004|01:00:00|   1.0|1136|      31| 3.3| 672|     62|1453|     76|1333| 730|10.7|60.0|0.7702|
|3/11/2004|02:00:00|   0.9|1094|      24| 2.3| 609|     45|1579|     60|1276| 620|10.7|59.7|0.7648|
|3/11/2004|03:00:00|   0.6|1010|      19| 1.7| 561|   NULL|1705|   NULL|1235| 501|10.3|60.2|0.7517|
|3/11/2004|04:00:00|  NULL|1011|      14| 1.3| 527|     21|1818|     34|1197| 445|10.1|60.5|0.7465|
|3/11/2004|05:00:00|   0.7|1066|       8| 1.1| 512|     16|1918|     28|1182| 422|11.0|56.2|0.7366|
|3/11/2004|06:00:00|   0.7|1052|      16| 1.6| 553|     34|1738|     48|1221| 472|10.5|58.1|0.7353|
|3/11/2004|07:00:00|   1.1|1144|      29| 3.2| 667|     98|1490|     82|1339| 730|10.2|59.6|0.7417|
|3/11/2004|08:00:00|   2.0|1333|      64| 8.0| 900|    174|1136|    112|1517|1102|10.8|57.4|0.7408|
|3/11/2004|09:00:00|   2.2|1351|      87| 9.5| 960|    129|1079|    101|1583|1028|10.5|60.6|0.7691|
|3/11/2004|10:00:00|   1.7|1233|      77| 6.3| 827|    112|1218|     98|1446| 860|10.8|58.4|0.7552|
|3/11/2004|11:00:00|   1.5|1179|      43| 5.0| 762|     95|1328|     92|1362| 671|10.5|57.9|0.7352|
|3/11/2004|12:00:00|   1.6|1236|      61| 5.2| 774|    104|1301|     95|1401| 664| 9.5|66.8|0.7951|
|3/11/2004|13:00:00|   1.9|1286|      63| 7.3| 869|    146|1162|    112|1537| 799| 8.3|76.4|0.8393|
+---------+--------+------+----+--------+----+----+-------+----+-------+----+----+----+----+------+
only showing top 20 rows

#### nulltest()

This method takes in an item of SparkDataCheck class and a specific column name from that item's df attribute. \
Then, a new column is appended providing True or False values for each row in the specified column, depending on if that value is NULL. \
This method returns the edited SparkDataCheck item, so .show() must be used to see the table.

In [22]:
airdata.nulltest("NO2(GT)").df.show()

+---------+--------+------+----+--------+----+----+-------+----+-------+----+----+----+----+------+---------------+
|     Date|    Time|CO(GT)|  CO|NMHC(GT)|   B|NMHC|NOx(GT)| NOx|NO2(GT)| NO2|  O3|   T|  RH|    AH|NO2(GT) is null|
+---------+--------+------+----+--------+----+----+-------+----+-------+----+----+----+----+------+---------------+
|3/10/2004|18:00:00|   2.6|1360|     150|11.9|1046|    166|1056|    113|1692|1268|13.6|48.9|0.7578|          false|
|3/10/2004|19:00:00|   2.0|1292|     112| 9.4| 955|    103|1174|     92|1559| 972|13.3|47.7|0.7255|          false|
|3/10/2004|20:00:00|   2.2|1402|      88| 9.0| 939|    131|1140|    114|1555|1074|11.9|54.0|0.7502|          false|
|3/10/2004|21:00:00|   2.2|1376|      80| 9.2| 948|    172|1092|    122|1584|1203|11.0|60.0|0.7867|          false|
|3/10/2004|22:00:00|   1.6|1272|      51| 6.5| 836|    131|1205|    116|1490|1110|11.2|59.6|0.7888|          false|
|3/10/2004|23:00:00|   1.2|1197|      38| 4.7| 750|     89|1337|     96|1393| 949|11.2|59.2|0.7848|          false|
|3/11/2004|00:00:00|   1.2|1185|      31| 3.6| 690|     62|1462|     77|1333| 733|11.3|56.8|0.7603|          false|
|3/11/2004|01:00:00|   1.0|1136|      31| 3.3| 672|     62|1453|     76|1333| 730|10.7|60.0|0.7702|          false|
|3/11/2004|02:00:00|   0.9|1094|      24| 2.3| 609|     45|1579|     60|1276| 620|10.7|59.7|0.7648|          false|
|3/11/2004|03:00:00|   0.6|1010|      19| 1.7| 561|   NULL|1705|   NULL|1235| 501|10.3|60.2|0.7517|           true|
|3/11/2004|04:00:00|  NULL|1011|      14| 1.3| 527|     21|1818|     34|1197| 445|10.1|60.5|0.7465|          false|
|3/11/2004|05:00:00|   0.7|1066|       8| 1.1| 512|     16|1918|     28|1182| 422|11.0|56.2|0.7366|          false|
|3/11/2004|06:00:00|   0.7|1052|      16| 1.6| 553|     34|1738|     48|1221| 472|10.5|58.1|0.7353|          false|
|3/11/2004|07:00:00|   1.1|1144|      29| 3.2| 667|     98|1490|     82|1339| 730|10.2|59.6|0.7417|          false|
|3/11/2004|08:00:00|   2.0|1333|      64| 8.0| 900|    174|1136|    112|1517|1102|10.8|57.4|0.7408|          false|
|3/11/2004|09:00:00|   2.2|1351|      87| 9.5| 960|    129|1079|    101|1583|1028|10.5|60.6|0.7691|          false|
|3/11/2004|10:00:00|   1.7|1233|      77| 6.3| 827|    112|1218|     98|1446| 860|10.8|58.4|0.7552|          false|
|3/11/2004|11:00:00|   1.5|1179|      43| 5.0| 762|     95|1328|     92|1362| 671|10.5|57.9|0.7352|          false|
|3/11/2004|12:00:00|   1.6|1236|      61| 5.2| 774|    104|1301|     95|1401| 664| 9.5|66.8|0.7951|          false|
|3/11/2004|13:00:00|   1.9|1286|      63| 7.3| 869|    146|1162|    112|1537| 799| 8.3|76.4|0.8393|          false|
+---------+--------+------+----+--------+----+----+-------+----+-------+----+----+----+----+------+---------------+
only showing top 20 rows

This method can be used pretty quickly to check counts of null values using .groupBy().

In [23]:
airdata.nulltest("NOx(GT)").df.groupBy("Time", "NOx(GT) is null").count().sort("Time").show()

+--------+---------------+-----+
|    Time|NOx(GT) is null|count|
+--------+---------------+-----+
|00:00:00|          false|  336|
|00:00:00|           true|   54|
|01:00:00|           true|   56|
|01:00:00|          false|  334|
|02:00:00|           true|   58|
|02:00:00|          false|  332|
|03:00:00|           true|  364|
|03:00:00|          false|   26|
|04:00:00|           true|   58|
|04:00:00|          false|  332|
|05:00:00|           true|   57|
|05:00:00|          false|  333|
|06:00:00|           true|   56|
|06:00:00|          false|  334|
|07:00:00|           true|   56|
|07:00:00|          false|  334|
|08:00:00|           true|   61|
|08:00:00|          false|  329|
|09:00:00|          false|  334|
|09:00:00|           true|   56|
+--------+---------------+-----+
only showing top 20 rows

In [24]:
airdata.nulltest("CO(GT)").df.groupBy("CO(GT) is null").count().show()

+--------------+-----+
|CO(GT) is null|count|
+--------------+-----+
|          true| 1683|
|         false| 7674|
+--------------+-----+

In [25]:
airdata.nulltest("B").df.show()

+---------+--------+------+----+--------+----+----+-------+----+-------+----+----+----+----+------+---------------+---------------+--------------+---------+
|     Date|    Time|CO(GT)|  CO|NMHC(GT)|   B|NMHC|NOx(GT)| NOx|NO2(GT)| NO2|  O3|   T|  RH|    AH|NO2(GT) is null|NOx(GT) is null|CO(GT) is null|B is null|
+---------+--------+------+----+--------+----+----+-------+----+-------+----+----+----+----+------+---------------+---------------+--------------+---------+
|3/10/2004|18:00:00|   2.6|1360|     150|11.9|1046|    166|1056|    113|1692|1268|13.6|48.9|0.7578|          false|          false|         false|    false|
|3/10/2004|19:00:00|   2.0|1292|     112| 9.4| 955|    103|1174|     92|1559| 972|13.3|47.7|0.7255|          false|          false|         false|    false|
|3/10/2004|20:00:00|   2.2|1402|      88| 9.0| 939|    131|1140|    114|1555|1074|11.9|54.0|0.7502|          false|          false|         false|    false|
|3/10/2004|21:00:00|   2.2|1376|      80| 9.2| 948|    172|1092|    122|1584|1203|11.0|60.0|0.7867|          false|          false|         false|    false|
|3/10/2004|22:00:00|   1.6|1272|      51| 6.5| 836|    131|1205|    116|1490|1110|11.2|59.6|0.7888|          false|          false|         false|    false|
|3/10/2004|23:00:00|   1.2|1197|      38| 4.7| 750|     89|1337|     96|1393| 949|11.2|59.2|0.7848|          false|          false|         false|    false|
|3/11/2004|00:00:00|   1.2|1185|      31| 3.6| 690|     62|1462|     77|1333| 733|11.3|56.8|0.7603|          false|          false|         false|    false|
|3/11/2004|01:00:00|   1.0|1136|      31| 3.3| 672|     62|1453|     76|1333| 730|10.7|60.0|0.7702|          false|          false|         false|    false|
|3/11/2004|02:00:00|   0.9|1094|      24| 2.3| 609|     45|1579|     60|1276| 620|10.7|59.7|0.7648|          false|          false|         false|    false|
|3/11/2004|03:00:00|   0.6|1010|      19| 1.7| 561|   NULL|1705|   NULL|1235| 501|10.3|60.2|0.7517|           true|           true|         false|    false|
|3/11/2004|04:00:00|  NULL|1011|      14| 1.3| 527|     21|1818|     34|1197| 445|10.1|60.5|0.7465|          false|          false|          true|    false|
|3/11/2004|05:00:00|   0.7|1066|       8| 1.1| 512|     16|1918|     28|1182| 422|11.0|56.2|0.7366|          false|          false|         false|    false|
|3/11/2004|06:00:00|   0.7|1052|      16| 1.6| 553|     34|1738|     48|1221| 472|10.5|58.1|0.7353|          false|          false|         false|    false|
|3/11/2004|07:00:00|   1.1|1144|      29| 3.2| 667|     98|1490|     82|1339| 730|10.2|59.6|0.7417|          false|          false|         false|    false|
|3/11/2004|08:00:00|   2.0|1333|      64| 8.0| 900|    174|1136|    112|1517|1102|10.8|57.4|0.7408|          false|          false|         false|    false|
|3/11/2004|09:00:00|   2.2|1351|      87| 9.5| 960|    129|1079|    101|1583|1028|10.5|60.6|0.7691|          false|          false|         false|    false|
|3/11/2004|10:00:00|   1.7|1233|      77| 6.3| 827|    112|1218|     98|1446| 860|10.8|58.4|0.7552|          false|          false|         false|    false|
|3/11/2004|11:00:00|   1.5|1179|      43| 5.0| 762|     95|1328|     92|1362| 671|10.5|57.9|0.7352|          false|          false|         false|    false|
|3/11/2004|12:00:00|   1.6|1236|      61| 5.2| 774|    104|1301|     95|1401| 664| 9.5|66.8|0.7951|          false|          false|         false|    false|
|3/11/2004|13:00:00|   1.9|1286|      63| 7.3| 869|    146|1162|    112|1537| 799| 8.3|76.4|0.8393|          false|          false|         false|    false|
+---------+--------+------+----+--------+----+----+-------+----+-------+----+----+----+----+------+---------------+---------------+--------------+---------+
only showing top 20 rows

### Summarization Methods

The methods below take in a SparkDataCheck object, and analyze it in different ways. Each returns a pandas data frame.

#### minmax()

This method accepts a specific column name, as well as a grouping variable, `groupvar`. It will return a pandas df containing the minimum and maximum values for the specified column within the SparkDataCheck df attribute, grouped by `groupvar` if one is provided. \
If no column is provided, this method will return a df of the min and max values for every numeric column in the object's df attribute, grouped if specified.

In [26]:
airdata.minmax("T")

<class 'str'>
Column Provided: True
Grouping Var Provided: False

   min(T)  max(T)
0    -1.9    44.6

As I did in the "Data Cleaning" section above, you can also use `.minmax()` to check for missing values in the data. Because -200 is far below the possible values for these variables, it would appear as the min value for any column with a missing value - using `.minmax()` and seeing no -200 values showed me that our replace method worked.

In [27]:
airdata.minmax()

<class 'NoneType'>
Column Provided: False
Grouping Var Provided: False

                       0
min(CO(GT))       0.1000
max(CO(GT))      11.9000
min(CO)         647.0000
max(CO)        2040.0000
min(NMHC(GT))     7.0000
max(NMHC(GT))  1189.0000
min(B)            0.1000
max(B)           63.7000
min(NMHC)       383.0000
max(NMHC)      2214.0000
min(NOx(GT))      2.0000
max(NOx(GT))   1479.0000
min(NOx)        322.0000
max(NOx)       2683.0000
min(NO2(GT))      2.0000
max(NO2(GT))    340.0000
min(NO2)        551.0000
max(NO2)       2775.0000
min(O3)         221.0000
max(O3)        2523.0000
min(T)           -1.9000
max(T)           44.6000
min(RH)           9.2000
max(RH)          88.7000
min(AH)           0.1847
max(AH)           2.2310

Here, I am chaining our `minmax()` method with a `.sort_values()` call, which helps sort the data by the column we want.

In [28]:
airdata.minmax("NOx", "Time").sort_values("Time")

<class 'str'>
Column Provided: True
Grouping Var Provided: True

        Time  min(NOx)  max(NOx)
8   00:00:00       443      1627
1   01:00:00       435      1900
0   02:00:00       497      1955
13  03:00:00       530      2081
14  04:00:00       508      2331
2   05:00:00       515      2559
4   06:00:00       534      2294
7   07:00:00       407      2683
15  08:00:00       370      2327
5   09:00:00       345      2318
6   10:00:00       411      2542
11  11:00:00       426      1716
18  12:00:00       413      1494
23  13:00:00       410      1502
19  14:00:00       390      1596
9   15:00:00       415      2121
3   16:00:00       392      1991
22  17:00:00       330      1773
16  18:00:00       322      1481
20  19:00:00       325      1798
12  20:00:00       330      1586
10  21:00:00       370      1732
21  22:00:00       417      1972
17  23:00:00       424      1729

This method can be useful when combined with the validation methods from earlier: \
I can create and use a new category in one line - Here, finding the min and max levels for RH at different B levels.

In [29]:
airdata.withinlimits("B", upper = 5).minmax("RH", groupvar = "B below 5")

<class 'str'>
Column Provided: True
Grouping Var Provided: True

  B below 5  min(RH)  max(RH)
0      None      NaN      NaN
1      True     10.0     87.2
2     False      9.2     88.7

#### strcount()

This method accepts a column name, and a second optional column name. It returns a pandas df with the count of occurences for each string that appears in that column. \
If two columns are supplied, it provides a pandas df with the count of each unique combination of the strings in each column.

In this first example, it's no surprise each date appears 24 times, once per hour.

In [30]:
airdata.strcount("Date")

           Date  count
0      9/2/2004     24
1    12/26/2004     24
2     2/18/2005     24
3    10/10/2004     24
4    10/11/2004     24
..          ...    ...
386   1/23/2005     24
387   6/28/2004     24
388   8/16/2004     24
389  12/20/2004     24
390    3/5/2005     24

[391 rows x 2 columns]

This method checks to make sure each column supplied is comprised of strings before running - If a non-string column is supplied, that information is printed.

In [31]:
airdata.strcount("Date", "CO")

Non-string second column supplied - No actions taken

In [32]:
airdata.strcount("NOx")

Non-string first column supplied - No actions taken

Here, again, no surprise that each combination of dates & times happens once.

In [33]:
airdata.strcount("Date", "Time")

          Date      Time  count
5189  1/1/2005  09:00:00      1
8201  1/1/2005  14:00:00      1
8627  1/1/2005  10:00:00      1
1901  1/1/2005  17:00:00      1
3070  1/1/2005  07:00:00      1
...        ...       ...    ...
6447  9/9/2004  23:00:00      1
625   9/9/2004  13:00:00      1
5128  9/9/2004  10:00:00      1
6582  9/9/2004  02:00:00      1
8841  9/9/2004  18:00:00      1

[9357 rows x 3 columns]

### Re-reading in the data

In [34]:
pandasairdata = pd.read_csv("air.csv")

In [39]:
pad = SparkDataCheck.frompdf(pandasairdata, spark)
pad.df.show()

+----------+---------+--------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+
|Unnamed: 0|     Date|    Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|
+----------+---------+--------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+
|         0|3/10/2004|18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578|
|         1|3/10/2004|19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255|
|         2|3/10/2004|20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502|
|         3|3/10/2004|21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867|
|         4|3/10/2004|22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888|
|         5|3/10/2004|23:00:00|   1.2|       1197|      38|     4.7|          750|     89|        1337|     96|        1393|        949|11.2|59.2|0.7848|
|         6|3/11/2004| 0:00:00|   1.2|       1185|      31|     3.6|          690|     62|        1462|     77|        1333|        733|11.3|56.8|0.7603|
|         7|3/11/2004| 1:00:00|   1.0|       1136|      31|     3.3|          672|     62|        1453|     76|        1333|        730|10.7|60.0|0.7702|
|         8|3/11/2004| 2:00:00|   0.9|       1094|      24|     2.3|          609|     45|        1579|     60|        1276|        620|10.7|59.7|0.7648|
|         9|3/11/2004| 3:00:00|   0.6|       1010|      19|     1.7|          561|   -200|        1705|   -200|        1235|        501|10.3|60.2|0.7517|
|        10|3/11/2004| 4:00:00|-200.0|       1011|      14|     1.3|          527|     21|        1818|     34|        1197|        445|10.1|60.5|0.7465|
|        11|3/11/2004| 5:00:00|   0.7|       1066|       8|     1.1|          512|     16|        1918|     28|        1182|        422|11.0|56.2|0.7366|
|        12|3/11/2004| 6:00:00|   0.7|       1052|      16|     1.6|          553|     34|        1738|     48|        1221|        472|10.5|58.1|0.7353|
|        13|3/11/2004| 7:00:00|   1.1|       1144|      29|     3.2|          667|     98|        1490|     82|        1339|        730|10.2|59.6|0.7417|
|        14|3/11/2004| 8:00:00|   2.0|       1333|      64|     8.0|          900|    174|        1136|    112|        1517|       1102|10.8|57.4|0.7408|
|        15|3/11/2004| 9:00:00|   2.2|       1351|      87|     9.5|          960|    129|        1079|    101|        1583|       1028|10.5|60.6|0.7691|
|        16|3/11/2004|10:00:00|   1.7|       1233|      77|     6.3|          827|    112|        1218|     98|        1446|        860|10.8|58.4|0.7552|
|        17|3/11/2004|11:00:00|   1.5|       1179|      43|     5.0|          762|     95|        1328|     92|        1362|        671|10.5|57.9|0.7352|
|        18|3/11/2004|12:00:00|   1.6|       1236|      61|     5.2|          774|    104|        1301|     95|        1401|        664| 9.5|66.8|0.7951|
|        19|3/11/2004|13:00:00|   1.9|       1286|      63|     7.3|          869|    146|        1162|    112|        1537|        799| 8.3|76.4|0.8393|
+----------+---------+--------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+
only showing top 20 rows

In [38]:
pad.withinlimits("CO(GT)", lower = 1, upper = 2).df.show()

+----------+---------+--------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------------------+
|Unnamed: 0|     Date|    Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|CO(GT) within (1,2)|
+----------+---------+--------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------------------+
|         0|3/10/2004|18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578|              false|
|         1|3/10/2004|19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255|               true|
|         2|3/10/2004|20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502|              false|
|         3|3/10/2004|21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867|              false|
|         4|3/10/2004|22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888|               true|
|         5|3/10/2004|23:00:00|   1.2|       1197|      38|     4.7|          750|     89|        1337|     96|        1393|        949|11.2|59.2|0.7848|               true|
|         6|3/11/2004| 0:00:00|   1.2|       1185|      31|     3.6|          690|     62|        1462|     77|        1333|        733|11.3|56.8|0.7603|               true|
|         7|3/11/2004| 1:00:00|   1.0|       1136|      31|     3.3|          672|     62|        1453|     76|        1333|        730|10.7|60.0|0.7702|               true|
|         8|3/11/2004| 2:00:00|   0.9|       1094|      24|     2.3|          609|     45|        1579|     60|        1276|        620|10.7|59.7|0.7648|              false|
|         9|3/11/2004| 3:00:00|   0.6|       1010|      19|     1.7|          561|   -200|        1705|   -200|        1235|        501|10.3|60.2|0.7517|              false|
|        10|3/11/2004| 4:00:00|-200.0|       1011|      14|     1.3|          527|     21|        1818|     34|        1197|        445|10.1|60.5|0.7465|              false|
|        11|3/11/2004| 5:00:00|   0.7|       1066|       8|     1.1|          512|     16|        1918|     28|        1182|        422|11.0|56.2|0.7366|              false|
|        12|3/11/2004| 6:00:00|   0.7|       1052|      16|     1.6|          553|     34|        1738|     48|        1221|        472|10.5|58.1|0.7353|              false|
|        13|3/11/2004| 7:00:00|   1.1|       1144|      29|     3.2|          667|     98|        1490|     82|        1339|        730|10.2|59.6|0.7417|               true|
|        14|3/11/2004| 8:00:00|   2.0|       1333|      64|     8.0|          900|    174|        1136|    112|        1517|       1102|10.8|57.4|0.7408|               true|
|        15|3/11/2004| 9:00:00|   2.2|       1351|      87|     9.5|          960|    129|        1079|    101|        1583|       1028|10.5|60.6|0.7691|              false|
|        16|3/11/2004|10:00:00|   1.7|       1233|      77|     6.3|          827|    112|        1218|     98|        1446|        860|10.8|58.4|0.7552|               true|
|        17|3/11/2004|11:00:00|   1.5|       1179|      43|     5.0|          762|     95|        1328|     92|        1362|        671|10.5|57.9|0.7352|               true|
|        18|3/11/2004|12:00:00|   1.6|       1236|      61|     5.2|          774|    104|        1301|     95|        1401|        664| 9.5|66.8|0.7951|               true|
|        19|3/11/2004|13:00:00|   1.9|       1286|      63|     7.3|          869|    146|        1162|    112|        1537|        799| 8.3|76.4|0.8393|               true|
+----------+---------+--------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------------------+
only showing top 20 rows

# Part II

Part II Description coming soon

Importing additional tools

In [2]:
import pyspark.pandas as ps

Let's set our spark session again:

In [19]:
spark = SparkSession.builder.appName('my_app').getOrCreate()

### Pandas on Spark

In [9]:
#spark.conf.set("spark.sql.ansi.enabled", "false")

And let's read in our csv:

In [89]:
nfl = ps.read_csv("weekly_nfl_data.csv")

Taking a look at our first 5 rows:

In [93]:
nfl[0:5]

    player_id player_name    player_display_name position position_group headshot_url recent_team  season  week season_type opponent_team  completions  attempts  passing_yards  passing_tds  interceptions  sacks  sack_yards  sack_fumbles  sack_fumbles_lost  passing_air_yards  passing_yards_after_catch  passing_first_downs  passing_epa  passing_2pt_conversions  pacr  dakota  carries  rushing_yards  rushing_tds  rushing_fumbles  rushing_fumbles_lost  rushing_first_downs  rushing_epa  rushing_2pt_conversions  receptions  targets  receiving_yards  receiving_tds  receiving_fumbles  receiving_fumbles_lost  receiving_air_yards  receiving_yards_after_catch  receiving_first_downs  receiving_epa  receiving_2pt_conversions  racr  target_share  air_yards_share  wopr  special_teams_tds  fantasy_points  fantasy_points_ppr
0  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         MIA    1999     1         REG           DEN            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN       16           60.0            1              0.0                   0.0                  4.0     6.248771                        0           1        1              7.0              0                0.0                     0.0                  0.0                          0.0                    0.0       0.292378                          0   0.0      0.052632              NaN   NaN                0.0            12.7                13.7
1  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         MIA    1999     2         REG           ARI            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN        9           33.0            0              0.0                   0.0                  1.0    -1.434950                        0           3        4             18.0              0                0.0                     0.0                  0.0                          0.0                    1.0       0.377009                          0   0.0      0.117647              NaN   NaN                0.0             5.1                 8.1
2  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         MIA    1999     4         REG           BUF            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN        3            2.0            0              0.0                   0.0                  0.0    -1.539952                        0           0        1              0.0              0                0.0                     0.0                  0.0                          0.0                    0.0      -0.699578                          0   NaN      0.023810              NaN   NaN                0.0             0.2                 0.2
3  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         CLE    1999     7         REG            LA            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN        6           27.0            0              0.0                   0.0                  0.0     0.216051                        0           2        2              8.0              0                0.0                     0.0                  0.0                          0.0                    0.0      -0.228454                          0   0.0      0.050000              NaN   NaN                0.0             3.5                 5.5
4  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         CLE    1999     8         REG            NO            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN       13           39.0            0              0.0                   0.0                  2.0    -2.972259                        0           0        0              0.0              0                0.0                     0.0                  0.0                          0.0                    0.0            NaN                          0   NaN           NaN              NaN   NaN                0.0             3.9                 3.9

And our column names:

In [94]:
nfl.columns

Index(['player_id', 'player_name', 'player_display_name', 'position',
       'position_group', 'headshot_url', 'recent_team', 'season', 'week',
       'season_type', 'opponent_team', 'completions', 'attempts',
       'passing_yards', 'passing_tds', 'interceptions', 'sacks', 'sack_yards',
       'sack_fumbles', 'sack_fumbles_lost', 'passing_air_yards',
       'passing_yards_after_catch', 'passing_first_downs', 'passing_epa',
       'passing_2pt_conversions', 'pacr', 'dakota', 'carries', 'rushing_yards',
       'rushing_tds', 'rushing_fumbles', 'rushing_fumbles_lost',
       'rushing_first_downs', 'rushing_epa', 'rushing_2pt_conversions',
       'receptions', 'targets', 'receiving_yards', 'receiving_tds',
       'receiving_fumbles', 'receiving_fumbles_lost', 'receiving_air_yards',
       'receiving_yards_after_catch', 'receiving_first_downs', 'receiving_epa',
       'receiving_2pt_conversions', 'racr', 'target_share', 'air_yards_share',
       'wopr', 'special_teams_tds', 'fantasy_points', 'fantasy_points_ppr'],
      dtype='object')

Per the instructions, here I am shrinking our df by keeping only rows for QBs in the regular season, from 2005-2023. \
Then, I am removing many columns we won't be needing for this project.

In [95]:
## QBs only, regular seasons 2005-2023

qb = nfl[(nfl["position"] == "QB") & (nfl["season_type"] == "REG") & (nfl["season"].between(2005,2023))] 

## Keeping columns we want.

qb = qb.loc[:,["player_display_name", "season", "week", "completions", "attempts", "passing_yards", "passing_tds", "interceptions"]]

Here, I will find the mean and sum for each player's season values, using the `.agg` function. \
I will also save this as a new object, so I can continue to work on it.

In [96]:
qbsummary = qb.groupby(["player_display_name", "season"]).agg(["sum", "mean"]).reset_index()
qbsummary[0:5]

  player_display_name season week            completions            attempts            passing_yards             passing_tds           interceptions
                              sum       mean         sum       mean      sum       mean           sum        mean         sum      mean           sum      mean
0       Jake Delhomme   2006   99   7.615385         263  20.230769      431  33.153846        2805.0  215.769231          17  1.307692          11.0  0.846154
1        Jake Plummer   2005  144   9.000000         277  17.312500      456  28.500000        3366.0  210.375000          18  1.125000           7.0  0.437500
2         Matt Schaub   2006   60  12.000000          18   3.600000       27   5.400000         208.0   41.600000           1  0.200000           2.0  0.400000
3         Vince Young   2006  143   9.533333         184  12.266667      356  23.733333        2199.0  146.600000          12  0.800000          13.0  0.866667
4       Kerry Collins   2007   48   8.000000          50   8.333333       82  13.666667         531.0   88.500000           0  0.000000           0.0  0.000000

Here I'm going to "flatten" my df and combine the two header rows. This will make the next steps easier!

In [97]:
qbsummary.columns = ['_'.join(col) for col in qbsummary.columns]
qbsummary[0:5]

  player_display_name_  season_  week_sum  week_mean  completions_sum  completions_mean  attempts_sum  attempts_mean  passing_yards_sum  passing_yards_mean  passing_tds_sum  passing_tds_mean  interceptions_sum  interceptions_mean
0        Jake Delhomme     2006        99   7.615385              263         20.230769           431      33.153846             2805.0          215.769231               17          1.307692               11.0            0.846154
1         Jake Plummer     2005       144   9.000000              277         17.312500           456      28.500000             3366.0          210.375000               18          1.125000                7.0            0.437500
2          Matt Schaub     2006        60  12.000000               18          3.600000            27       5.400000              208.0           41.600000                1          0.200000                2.0            0.400000
3          Vince Young     2006       143   9.533333              184         12.266667           356      23.733333             2199.0          146.600000               12          0.800000               13.0            0.866667
4        Kerry Collins     2007        48   8.000000               50          8.333333            82      13.666667              531.0           88.500000                0          0.000000                0.0            0.000000

Here I'm adding two new columns, **Completion Percentage** and **TD-Int ratio**

In [98]:
qbsummary["completion_percentage"] = (qbsummary["completions_sum"]/qbsummary["attempts_sum"])
qbsummary["td_int_ratio"] = (qbsummary["passing_tds_sum"]/qbsummary["interceptions_sum"])
qbsummary[0:5]

  player_display_name_  season_  week_sum  week_mean  completions_sum  completions_mean  attempts_sum  attempts_mean  passing_yards_sum  passing_yards_mean  passing_tds_sum  passing_tds_mean  interceptions_sum  interceptions_mean  completion_percentage  td_int_ratio
0        Jake Delhomme     2006        99   7.615385              263         20.230769           431      33.153846             2805.0          215.769231               17          1.307692               11.0            0.846154               0.610209      1.545455
1         Jake Plummer     2005       144   9.000000              277         17.312500           456      28.500000             3366.0          210.375000               18          1.125000                7.0            0.437500               0.607456      2.571429
2          Matt Schaub     2006        60  12.000000               18          3.600000            27       5.400000              208.0           41.600000                1          0.200000                2.0            0.400000               0.666667      0.500000
3          Vince Young     2006       143   9.533333              184         12.266667           356      23.733333             2199.0          146.600000               12          0.800000               13.0            0.866667               0.516854      0.923077
4        Kerry Collins     2007        48   8.000000               50          8.333333            82      13.666667              531.0           88.500000                0          0.000000                0.0            0.000000               0.609756           NaN

Now I'm going to subset to only rows with 50+ attempts, and display our top 40 values of **Completion Percentage**, and then **TD-Int Ratio** in the following cell.

In [99]:
qbsummary = qbsummary[qbsummary["attempts_sum"] >= 50]
qbsummary.sort_values("completion_percentage", ascending = False)[0:40]

     player_display_name_  season_  week_sum  week_mean  completions_sum  completions_mean  attempts_sum  attempts_mean  passing_yards_sum  passing_yards_mean  passing_tds_sum  passing_tds_mean  interceptions_sum  interceptions_mean  completion_percentage  td_int_ratio
1409        C.J. Beathard     2023        65  10.833333               40          6.666667            53       8.833333              349.0           58.166667                1          0.166667                0.0            0.000000               0.754717           inf
1248           Colt McCoy     2021        62   8.857143               74         10.571429            99      14.142857              740.0          105.714286                3          0.428571                1.0            0.142857               0.747475      3.000000
900           Matt Schaub     2019        52  10.400000               50         10.000000            67      13.400000              580.0          116.000000                3          0.600000                1.0            0.200000               0.746269      3.000000
953            Drew Brees     2018       130   8.666667              364         24.266667           489      32.600000             3992.0          266.133333               32          2.133333                5.0            0.333333               0.744376      6.400000
1057           Drew Brees     2019       119  10.818182              281         25.545455           378      34.363636             2979.0          270.818182               27          2.454545                4.0            0.363636               0.743386      6.750000
1338        Mason Rudolph     2023        66  16.500000               55         13.750000            74      18.500000              719.0          179.750000                3          0.750000                0.0            0.000000               0.743243           inf
1133          Taysom Hill     2020       147   9.187500               88          5.500000           121       7.562500              928.0           58.000000                4          0.250000                2.0            0.125000               0.727273      2.000000
1007           Nick Foles     2018        51  10.200000              141         28.200000           195      39.000000             1413.0          282.600000                7          1.400000                4.0            0.800000               0.723077      1.750000
917            Drew Brees     2017       148   9.250000              386         24.125000           536      33.500000             4334.0          270.875000               23          1.437500                8.0            0.500000               0.720149      2.875000
851          Sam Bradford     2016       146   9.733333              395         26.333333           552      36.800000             3877.0          258.466667               20          1.333333                5.0            0.333333               0.715580      4.000000
510            Drew Brees     2011       142   8.875000              471         29.437500           660      41.250000             5535.0          345.937500               46          2.875000               14.0            0.875000               0.713636      3.285714
838            Colt McCoy     2014        57  11.400000               91         18.200000           128      25.600000             1057.0          211.400000                4          0.800000                3.0            0.600000               0.710938      1.333333
1262        Aaron Rodgers     2020       148   9.250000              372         23.250000           526      32.875000             4299.0          268.687500               48          3.000000                5.0            0.312500               0.707224      9.600000
1453         Bailey Zappe     2022        22   5.500000               65         16.250000            92      23.000000              781.0          195.250000                5          1.250000                3.0            0.750000               0.706522      1.666667
242            Drew Brees     2009       131   8.733333              363         24.200000           514      34.266667             4388.0          292.533333               34          2.266667               11.0            0.733333               0.706226      3.090909
1098           Drew Brees     2020        97   8.083333              275         22.916667           390      32.500000             2942.0          245.166667               24          2.000000                6.0            0.500000               0.705128      4.000000
1437           Joe Burrow     2021       143   8.937500              366         22.875000           520      32.500000             4611.0          288.187500               34          2.125000               14.0            0.875000               0.703846      2.428571
1101           Derek Carr     2019       147   9.187500              361         22.562500           513      32.062500             4054.0          253.375000               21          1.312500                8.0            0.500000               0.703704      2.625000
1303        Jake Browning     2023       117  13.000000              171         19.000000           243      27.000000             1936.0          215.111111               12          1.333333                7.0            0.777778               0.703704      1.714286
901          Chase Daniel     2019        20   6.666667               45         15.000000            64      21.333333              435.0          145.000000                3          1.000000                2.0            0.666667               0.703125      1.500000
1079       Ryan Tannehill     2019       128  10.666667              201         16.750000           286      23.833333             2742.0          228.500000               22          1.833333                6.0            0.500000               0.702797      3.666667
1088       Deshaun Watson     2020       145   9.062500              382         23.875000           544      34.000000             4823.0          301.437500               33          2.062500                7.0            0.437500               0.702206      4.714286
503            Alex Smith     2012        63   6.300000              153         15.300000           218      21.800000             1737.0          173.700000               13          1.300000                5.0            0.500000               0.701835      2.600000
942          Kirk Cousins     2018       143   8.937500              425         26.562500           606      37.875000             4298.0          268.625000               30          1.875000               10.0            0.625000               0.701320      3.000000
129          Jamie Martin     2005        92  11.500000              124         15.500000           177      22.125000             1277.0          159.625000                5          0.625000                7.0            0.875000               0.700565      0.714286
884            Drew Brees     2016       148   9.250000              471         29.437500           673      42.062500             5208.0          325.500000               37          2.312500               15.0            0.937500               0.699851      2.466667
770             Tony Romo     2014       133   8.866667              304         20.266667           435      29.000000             3705.0          247.000000               34          2.266667                9.0            0.600000               0.698851      3.777778
872             Matt Ryan     2016       142   8.875000              373         23.312500           534      33.375000             4944.0          309.000000               38          2.375000                7.0            0.437500               0.698502      5.428571
876          Kirk Cousins     2015       145   9.062500              379         23.687500           543      33.937500             4166.0          260.375000               29          1.812500               11.0            0.687500               0.697974      2.636364
1316           Geno Smith     2022       160   9.411765              399         23.470588           572      33.647059             4282.0          251.882353               30          1.764706               11.0            0.647059               0.697552      2.727273
926          Chase Daniel     2018        38   9.500000               53         13.250000            76      19.000000              515.0          128.750000                3          0.750000                2.0            0.500000               0.697368      1.500000
914          Carson Wentz     2018        93   8.454545              279         25.363636           401      36.454545             3074.0          279.454545               21          1.909091                7.0            0.636364               0.695761      3.000000
1397         Dak Prescott     2023       164   9.647059              410         24.117647           590      34.705882             4516.0          265.647059               36          2.117647                9.0            0.529412               0.694915      4.000000
553         Philip Rivers     2013       145   9.062500              378         23.625000           544      34.000000             4478.0          279.875000               32          2.000000               11.0            0.687500               0.694853      2.909091
362             Tony Romo     2010        24   4.000000              148         24.666667           213      35.500000             1605.0          267.500000               11          1.833333                7.0            1.166667               0.694836      1.571429
1295         Kirk Cousins     2023        36   4.500000              216         27.000000           311      38.875000             2331.0          291.375000               18          2.250000                5.0            0.625000               0.694534      3.600000
928             Matt Ryan     2018       145   9.062500              422         26.375000           608      38.000000             4924.0          307.750000               35          2.187500                7.0            0.437500               0.694079      5.000000
1433          Brock Purdy     2023       144   9.000000              308         19.250000           444      27.750000             4280.0          267.500000               31          1.937500               11.0            0.687500               0.693694      2.818182
41              Jim Sorgi     2005        57  11.400000               43          8.600000            62      12.400000              444.0           88.800000                3          0.600000                1.0            0.200000               0.693548      3.000000
772        Brandon Weeden     2015        45   7.500000               97         16.166667           140      23.333333             1043.0          173.833333                5          0.833333                2.0            0.333333               0.692857      2.500000

Wow! A couple infinite values because they had no interceptions!

In [100]:
qbsummary.sort_values("td_int_ratio", ascending = False)[0:40]

     player_display_name_  season_  week_sum  week_mean  completions_sum  completions_mean  attempts_sum  attempts_mean  passing_yards_sum  passing_yards_mean  passing_tds_sum  passing_tds_mean  interceptions_sum  interceptions_mean  completion_percentage  td_int_ratio
6           Charlie Batch     2006        71  10.142857               30          4.285714            52       7.428571              477.0           68.142857                5          0.714286                0.0            0.000000               0.576923           inf
26            Matt Schaub     2005        65   9.285714               33          4.714286            64       9.142857              495.0           70.714286                4          0.571429                0.0            0.000000               0.515625           inf
73           Todd Collins     2007        62  15.500000               67         16.750000           105      26.250000              888.0          222.000000                5          1.250000                0.0            0.000000               0.638095           inf
455            Troy Smith     2007        62  15.500000               40         10.000000            76      19.000000              452.0          113.000000                2          0.500000                0.0            0.000000               0.526316           inf
520           Jake Locker     2011        51  10.200000               34          6.800000            66      13.200000              542.0          108.400000                4          0.800000                0.0            0.000000               0.515152           inf
775           Brian Hoyer     2016        27   4.500000              134         22.333333           200      33.333333             1445.0          240.833333                6          1.000000                0.0            0.000000               0.670000           inf
778            Nick Foles     2016        17   8.500000               36         18.000000            55      27.500000              410.0          205.000000                3          1.500000                0.0            0.000000               0.654545           inf
812        Derek Anderson     2014        30   6.000000               65         13.000000            97      19.400000              701.0          140.200000                5          1.000000                0.0            0.000000               0.670103           inf
940       Jimmy Garoppolo     2016        49   8.166667               43          7.166667            63      10.500000              502.0           83.666667                4          0.666667                0.0            0.000000               0.682540           inf
984            Matt Moore     2019        54   9.000000               59          9.833333            91      15.166667              659.0          109.833333                4          0.666667                0.0            0.000000               0.648352           inf
1127        C.J. Beathard     2020        67  11.166667               66         11.000000           104      17.333333              787.0          131.166667                6          1.000000                0.0            0.000000               0.634615           inf
1334          Andy Dalton     2023         8   4.000000               34         17.000000            58      29.000000              361.0          180.500000                2          1.000000                0.0            0.000000               0.586207           inf
1338        Mason Rudolph     2023        66  16.500000               55         13.750000            74      18.500000              719.0          179.750000                3          0.750000                0.0            0.000000               0.743243           inf
1365       Desmond Ridder     2022        66  16.500000               73         18.250000           115      28.750000              708.0          177.000000                2          0.500000                0.0            0.000000               0.634783           inf
1409        C.J. Beathard     2023        65  10.833333               40          6.666667            53       8.833333              349.0           58.166667                1          0.166667                0.0            0.000000               0.754717           inf
763             Tom Brady     2016       134  11.166667              291         24.250000           432      36.000000             3554.0          296.166667               28          2.333333                2.0            0.166667               0.673611     14.000000
639            Nick Foles     2013       129   9.923077              203         15.615385           317      24.384615             2891.0          222.384615               27          2.076923                2.0            0.153846               0.640379     13.500000
618           Josh McCown     2013        92  11.500000              149         18.625000           224      28.000000             1829.0          228.625000               13          1.625000                1.0            0.125000               0.665179     13.000000
989         Aaron Rodgers     2018       146   9.125000              372         23.250000           597      37.312500             4442.0          277.625000               25          1.562500                2.0            0.125000               0.623116     12.500000
200           Damon Huard     2006        69   6.900000              148         14.800000           244      24.400000             1878.0          187.800000               11          1.100000                1.0            0.100000               0.606557     11.000000
1262        Aaron Rodgers     2020       148   9.250000              372         23.250000           526      32.875000             4299.0          268.687500               48          3.000000                5.0            0.312500               0.707224      9.600000
1111        Aaron Rodgers     2021       149   9.312500              366         22.875000           531      33.187500             4115.0          257.187500               37          2.312500                4.0            0.250000               0.689266      9.250000
286             Tom Brady     2010       148   9.250000              324         20.250000           492      30.750000             3900.0          243.750000               36          2.250000                4.0            0.250000               0.658537      9.000000
20          Jake Delhomme     2007         6   2.000000               55         18.333333            86      28.666667              617.0          205.666667                8          2.666667                1.0            0.333333               0.639535      8.000000
695         Aaron Rodgers     2014       144   9.000000              341         21.312500           520      32.500000             4381.0          273.812500               38          2.375000                5.0            0.312500               0.655769      7.600000
662         Aaron Rodgers     2011       128   8.533333              342         22.800000           501      33.400000             4636.0          309.066667               45          3.000000                6.0            0.400000               0.682635      7.500000
1057           Drew Brees     2019       119  10.818182              281         25.545455           378      34.363636             2979.0          270.818182               27          2.454545                4.0            0.363636               0.743386      6.750000
1073        Aaron Rodgers     2019       142   8.875000              353         22.062500           569      35.562500             4002.0          250.125000               26          1.625000                4.0            0.250000               0.620387      6.500000
953            Drew Brees     2018       130   8.666667              364         24.266667           489      32.600000             3992.0          266.133333               32          2.133333                5.0            0.333333               0.744376      6.400000
1267      Patrick Mahomes     2020       126   8.400000              390         26.000000           588      39.200000             4740.0          316.000000               38          2.533333                6.0            0.400000               0.663265      6.333333
145             Tom Brady     2007       143   8.937500              398         24.875000           578      36.125000             4806.0          300.375000               50          3.125000                8.0            0.500000               0.688581      6.250000
951        Russell Wilson     2019       142   8.875000              341         21.312500           516      32.250000             4110.0          256.875000               31          1.937500                5.0            0.312500               0.660853      6.200000
23          David Garrard     2007       105   8.750000              208         17.333333           325      27.083333             2509.0          209.083333               18          1.500000                3.0            0.250000               0.640000      6.000000
418      Matthew Stafford     2010        26   6.500000               57         14.250000            96      24.000000              535.0          133.750000                6          1.500000                1.0            0.250000               0.593750      6.000000
1168        Lamar Jackson     2019       128   8.533333              265         17.666667           401      26.733333             3127.0          208.466667               36          2.400000                6.0            0.400000               0.660848      6.000000
1026         Dak Prescott     2016       146   9.125000              311         19.437500           459      28.687500             3667.0          229.187500               23          1.437500                4.0            0.250000               0.677560      5.750000
766         Aaron Rodgers     2016       149   9.312500              401         25.062500           610      38.125000             4428.0          276.750000               40          2.500000                7.0            0.437500               0.657377      5.714286
673        Peyton Manning     2013       144   9.000000              450         28.125000           659      41.187500             5477.0          342.312500               55          3.437500               10.0            0.625000               0.682853      5.500000
872             Matt Ryan     2016       142   8.875000              373         23.312500           534      33.375000             4944.0          309.000000               38          2.375000                7.0            0.437500               0.698502      5.428571
1038           Alex Smith     2017       126   8.400000              341         22.733333           505      33.666667             4042.0          269.466667               26          1.733333                5.0            0.333333               0.675248      5.200000

### Spark SQL DataFrame

Here, I'm doing everything I did above, but in the Spark SQL DataFrame format, as opposed to the pandas-on-spark version above.

Reading in the data, and making sure its the proper type:

In [101]:
sql_nfl = spark.read.load("weekly_nfl_data.csv", format = "csv", sep = ",", inferSchema = "true", header = "true")
type(sql_nfl)

pyspark.sql.classic.dataframe.DataFrame

Taking a look at the first 5 rows - Bit hard to look at, but if you zoom (way) out, it's a normal df.

In [102]:
sql_nfl.show(5)

+----------+-----------+--------------------+--------+--------------+------------+-----------+------+----+-----------+-------------+-----------+--------+-------------+-----------+-------------+-----+----------+------------+-----------------+-----------------+-------------------------+-------------------+-----------+-----------------------+----+------+-------+-------------+-----------+---------------+--------------------+-------------------+-----------+-----------------------+----------+-------+---------------+-------------+-----------------+----------------------+-------------------+---------------------------+---------------------+-------------+-------------------------+----+------------+---------------+----+-----------------+--------------+------------------+
| player_id|player_name| player_display_name|position|position_group|headshot_url|recent_team|season|week|season_type|opponent_team|completions|attempts|passing_yards|passing_tds|interceptions|sacks|sack_yards|sack_fumbles|sack_fumbles_lost|passing_air_yards|passing_yards_after_catch|passing_first_downs|passing_epa|passing_2pt_conversions|pacr|dakota|carries|rushing_yards|rushing_tds|rushing_fumbles|rushing_fumbles_lost|rushing_first_downs|rushing_epa|rushing_2pt_conversions|receptions|targets|receiving_yards|receiving_tds|receiving_fumbles|receiving_fumbles_lost|receiving_air_yards|receiving_yards_after_catch|receiving_first_downs|receiving_epa|receiving_2pt_conversions|racr|target_share|air_yards_share|wopr|special_teams_tds|fantasy_points|fantasy_points_ppr|
+----------+-----------+--------------------+--------+--------------+------------+-----------+------+----+-----------+-------------+-----------+--------+-------------+-----------+-------------+-----+----------+------------+-----------------+-----------------+-------------------------+-------------------+-----------+-----------------------+----+------+-------+-------------+-----------+---------------+--------------------+-------------------+-----------+-----------------------+----------+-------+---------------+-------------+-----------------+----------------------+-------------------+---------------------------+---------------------+-------------+-------------------------+----+------------+---------------+----+-----------------+--------------+------------------+
|00-0000003|       NULL|Abdul-Karim al-Ja...|      RB|            RB|        NULL|        MIA|  1999|   1|        REG|          DEN|          0|       0|          0.0|          0|          0.0|  0.0|       0.0|           0|                0|              0.0|                      0.0|                0.0|       NULL|                      0|NULL|  NULL|     16|         60.0|          1|            0.0|                 0.0|                4.0|   6.248771|                      0|         1|      1|            7.0|            0|              0.0|                   0.0|                0.0|                        0.0|                  0.0|   0.29237816|                        0| 0.0|  0.05263158|           NULL|NULL|              0.0|          12.7|              13.7|
|00-0000003|       NULL|Abdul-Karim al-Ja...|      RB|            RB|        NULL|        MIA|  1999|   2|        REG|          ARI|          0|       0|          0.0|          0|          0.0|  0.0|       0.0|           0|                0|              0.0|                      0.0|                0.0|       NULL|                      0|NULL|  NULL|      9|         33.0|          0|            0.0|                 0.0|                1.0| -1.4349501|                      0|         3|      4|           18.0|            0|              0.0|                   0.0|                0.0|                        0.0|                  1.0|    0.3770089|                        0| 0.0|  0.11764706|           NULL|NULL|              0.0|           5.1|               8.1|
|00-0000003|       NULL|Abdul-Karim al-Ja...|      RB|            RB|        NULL|        MIA|  1999|   4|        REG|          BUF|          0|       0|          0.0|          0|          0.0|  0.0|       0.0|           0|                0|              0.0|                      0.0|                0.0|       NULL|                      0|NULL|  NULL|      3|          2.0|          0|            0.0|                 0.0|                0.0| -1.5399517|                      0|         0|      1|            0.0|            0|              0.0|                   0.0|                0.0|                        0.0|                  0.0|  -0.69957775|                        0|NULL| 0.023809524|           NULL|NULL|              0.0|           0.2|               0.2|
|00-0000003|       NULL|Abdul-Karim al-Ja...|      RB|            RB|        NULL|        CLE|  1999|   7|        REG|           LA|          0|       0|          0.0|          0|          0.0|  0.0|       0.0|           0|                0|              0.0|                      0.0|                0.0|       NULL|                      0|NULL|  NULL|      6|         27.0|          0|            0.0|                 0.0|                0.0|  0.2160509|                      0|         2|      2|            8.0|            0|              0.0|                   0.0|                0.0|                        0.0|                  0.0|  -0.22845396|                        0| 0.0|        0.05|           NULL|NULL|              0.0|           3.5|               5.5|
|00-0000003|       NULL|Abdul-Karim al-Ja...|      RB|            RB|        NULL|        CLE|  1999|   8|        REG|           NO|          0|       0|          0.0|          0|          0.0|  0.0|       0.0|           0|                0|              0.0|                      0.0|                0.0|       NULL|                      0|NULL|  NULL|     13|         39.0|          0|            0.0|                 0.0|                2.0| -2.9722588|                      0|         0|      0|            0.0|            0|              0.0|                   0.0|                0.0|                        0.0|                  0.0|         NULL|                        0|NULL|        NULL|           NULL|NULL|              0.0|           3.9|               3.9|
+----------+-----------+--------------------+--------+--------------+------------+-----------+------+----+-----------+-------------+-----------+--------+-------------+-----------+-------------+-----+----------+------------+-----------------+-----------------+-------------------------+-------------------+-----------+-----------------------+----+------+-------+-------------+-----------+---------------+--------------------+-------------------+-----------+-----------------------+----------+-------+---------------+-------------+-----------------+----------------------+-------------------+---------------------------+---------------------+-------------+-------------------------+----+------------+---------------+----+-----------------+--------------+------------------+
only showing top 5 rows

Column names:

In [ ]:
sql_nfl.columns

['player_id',
 'player_name',
 'player_display_name',
 'position',
 'position_group',
 'headshot_url',
 'recent_team',
 'season',
 'week',
 'season_type',
 'opponent_team',
 'completions',
 'attempts',
 'passing_yards',
 'passing_tds',
 'interceptions',
 'sacks',
 'sack_yards',
 'sack_fumbles',
 'sack_fumbles_lost',
 'passing_air_yards',
 'passing_yards_after_catch',
 'passing_first_downs',
 'passing_epa',
 'passing_2pt_conversions',
 'pacr',
 'dakota',
 'carries',
 'rushing_yards',
 'rushing_tds',
 'rushing_fumbles',
 'rushing_fumbles_lost',
 'rushing_first_downs',
 'rushing_epa',
 'rushing_2pt_conversions',
 'receptions',
 'targets',
 'receiving_yards',
 'receiving_tds',
 'receiving_fumbles',
 'receiving_fumbles_lost',
 'receiving_air_yards',
 'receiving_yards_after_catch',
 'receiving_first_downs',
 'receiving_epa',
 'receiving_2pt_conversions',
 'racr',
 'target_share',
 'air_yards_share',
 'wopr',
 'special_teams_tds',
 'fantasy_points',
 'fantasy_points_ppr']

Subsetting by position, year, season type, and choosing the columns we want: \
*so efficient, just one line of code!*

In [112]:
sql_qb = sql_nfl.filter(
    (sql_nfl["position"] == "QB") & 
    (sql_nfl["season_type"] == "REG") & 
    (sql_nfl["season"].between(2005, 2023)))\
    .select(
    "player_display_name", 
    "season", 
    "week", 
    "completions", 
    "attempts", 
    "passing_yards", 
    "passing_tds", 
    "interceptions")

sql_qb.show(5)

+-------------------+------+----+-----------+--------+-------------+-----------+-------------+
|player_display_name|season|week|completions|attempts|passing_yards|passing_tds|interceptions|
+-------------------+------+----+-----------+--------+-------------+-----------+-------------+
|         Tony Banks|  2005|  17|         14|      25|        173.0|          1|          2.0|
|      Charlie Batch|  2005|   9|          9|      16|         65.0|          0|          1.0|
|      Charlie Batch|  2005|  10|         13|      19|        150.0|          0|          0.0|
|      Charlie Batch|  2005|  16|          1|       1|         31.0|          1|          0.0|
|         Jeff Blake|  2005|   2|          1|       1|         11.0|          0|          0.0|
+-------------------+------+----+-----------+--------+-------------+-----------+-------------+
only showing top 5 rows

This step is pretty involved - \

* I am creating a grouped dataframe for each combination of `player_display_name` and `season`, with the sums of the other variables. \
* I am then left-joining that with a second df of the same grouping, but with means instead of sums. \
* Next, I am dropping the sum and average of season columns (We didn't want that one, but it was easier to do it this way) \
* Finally, I am using `.show()` to print the top 5 rows.

In [114]:
sql_qbsummary = sql_qb.groupBy(["player_display_name", "season"]).sum()\
        .join(sql_qb.groupBy(["player_display_name", "season"]).mean(),
              on = ["player_display_name", "season"], how = "left")\
        .drop("sum(season)", "avg(season)")

sql_qbsummary.show(5)

+-------------------+------+---------+----------------+-------------+------------------+----------------+------------------+-----------------+------------------+------------------+------------------+------------------+------------------+
|player_display_name|season|sum(week)|sum(completions)|sum(attempts)|sum(passing_yards)|sum(passing_tds)|sum(interceptions)|        avg(week)|  avg(completions)|     avg(attempts)|avg(passing_yards)|  avg(passing_tds)|avg(interceptions)|
+-------------------+------+---------+----------------+-------------+------------------+----------------+------------------+-----------------+------------------+------------------+------------------+------------------+------------------+
|      Jake Delhomme|  2006|       99|             263|          431|            2805.0|              17|              11.0|7.615384615384615| 20.23076923076923| 33.15384615384615|215.76923076923077|1.3076923076923077|0.8461538461538461|
|       Jake Plummer|  2005|      144|             277|          456|            3366.0|              18|               7.0|              9.0|           17.3125|              28.5|           210.375|             1.125|            0.4375|
|        Matt Schaub|  2006|       60|              18|           27|             208.0|               1|               2.0|             12.0|               3.6|               5.4|              41.6|               0.2|               0.4|
|        Vince Young|  2006|      143|             184|          356|            2199.0|              12|              13.0|9.533333333333333|12.266666666666667|23.733333333333334|             146.6|               0.8|0.8666666666666667|
|      Kerry Collins|  2007|       48|              50|           82|             531.0|               0|               0.0|              8.0| 8.333333333333334|13.666666666666666|              88.5|               0.0|               0.0|
+-------------------+------+---------+----------------+-------------+------------------+----------------+------------------+-----------------+------------------+------------------+------------------+------------------+------------------+
only showing top 5 rows

Next, we are recreating our two new stats - Completion percentage, and TD-Int ratio.\
We will do this using `.withColumn()` to specify our new column info. \
\
Here, note that when dividing by zero for "td_int_ratio", Spark SQL produces a `NULL` value, instead of the `inf` value we got with pandas-on-Spark.

In [116]:
sql_qbsummary = sql_qbsummary.withColumn("completion_percentage", 
                         (sql_qbsummary["sum(completions)"] / sql_qbsummary["sum(attempts)"]))\
            .withColumn("td_int_ratio", (sql_qbsummary["sum(passing_tds)"]/sql_qbsummary["sum(interceptions)"]))

sql_qbsummary.show(5)

+-------------------+------+---------+----------------+-------------+------------------+----------------+------------------+-----------------+------------------+------------------+------------------+------------------+------------------+---------------------+------------------+
|player_display_name|season|sum(week)|sum(completions)|sum(attempts)|sum(passing_yards)|sum(passing_tds)|sum(interceptions)|        avg(week)|  avg(completions)|     avg(attempts)|avg(passing_yards)|  avg(passing_tds)|avg(interceptions)|completion_percentage|      td_int_ratio|
+-------------------+------+---------+----------------+-------------+------------------+----------------+------------------+-----------------+------------------+------------------+------------------+------------------+------------------+---------------------+------------------+
|      Jake Delhomme|  2006|       99|             263|          431|            2805.0|              17|              11.0|7.615384615384615| 20.23076923076923| 33.15384615384615|215.76923076923077|1.3076923076923077|0.8461538461538461|   0.6102088167053364|1.5454545454545454|
|       Jake Plummer|  2005|      144|             277|          456|            3366.0|              18|               7.0|              9.0|           17.3125|              28.5|           210.375|             1.125|            0.4375|   0.6074561403508771|2.5714285714285716|
|        Matt Schaub|  2006|       60|              18|           27|             208.0|               1|               2.0|             12.0|               3.6|               5.4|              41.6|               0.2|               0.4|   0.6666666666666666|               0.5|
|        Vince Young|  2006|      143|             184|          356|            2199.0|              12|              13.0|9.533333333333333|12.266666666666667|23.733333333333334|             146.6|               0.8|0.8666666666666667|   0.5168539325842697|0.9230769230769231|
|      Kerry Collins|  2007|       48|              50|           82|             531.0|               0|               0.0|              8.0| 8.333333333333334|13.666666666666666|              88.5|               0.0|               0.0|   0.6097560975609756|              NULL|
+-------------------+------+---------+----------------+-------------+------------------+----------------+------------------+-----------------+------------------+------------------+------------------+------------------+------------------+---------------------+------------------+
only showing top 5 rows

Next, we are removing any QB instance where they had less than 50 attempts in the season. \
*See ya later 2006 Matt Schaub!*

In [117]:
sql_qbsummary = sql_qbsummary.filter(F.col("sum(attempts)") >= 50)
sql_qbsummary.show()

+-------------------+------+---------+----------------+-------------+------------------+----------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+---------------------+------------------+
|player_display_name|season|sum(week)|sum(completions)|sum(attempts)|sum(passing_yards)|sum(passing_tds)|sum(interceptions)|         avg(week)|  avg(completions)|     avg(attempts)|avg(passing_yards)|  avg(passing_tds)|avg(interceptions)|completion_percentage|      td_int_ratio|
+-------------------+------+---------+----------------+-------------+------------------+----------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+---------------------+------------------+
|      Jake Delhomme|  2006|       99|             263|          431|            2805.0|              17|              11.0| 7.615384615384615| 20.23076923076923| 33.15384615384615|215.76923076923077|1.3076923076923077|0.8461538461538461|   0.6102088167053364|1.5454545454545454|
|       Jake Plummer|  2005|      144|             277|          456|            3366.0|              18|               7.0|               9.0|           17.3125|              28.5|           210.375|             1.125|            0.4375|   0.6074561403508771|2.5714285714285716|
|        Vince Young|  2006|      143|             184|          356|            2199.0|              12|              13.0| 9.533333333333333|12.266666666666667|23.733333333333334|             146.6|               0.8|0.8666666666666667|   0.5168539325842697|0.9230769230769231|
|      Kerry Collins|  2007|       48|              50|           82|             531.0|               0|               0.0|               8.0| 8.333333333333334|13.666666666666666|              88.5|               0.0|               0.0|   0.6097560975609756|              NULL|
|      Charlie Batch|  2006|       71|              30|           52|             477.0|               5|               0.0|10.142857142857142| 4.285714285714286| 7.428571428571429| 68.14285714285714|0.7142857142857143|               0.0|   0.5769230769230769|              NULL|
|        Eli Manning|  2006|      149|             301|          522|            3244.0|              25|              18.0|            9.3125|           18.8125|            32.625|            202.75|            1.5625|             1.125|   0.5766283524904214|1.3888888888888888|
|       Mark Brunell|  2006|       64|             162|          261|            1789.0|               8|               4.0|               6.4|              16.2|              26.1|             178.9|               0.8|               0.4|   0.6206896551724138|               2.0|
|         Shaun Hill|  2007|       45|              54|           80|             501.0|               5|               2.0|              15.0|              18.0|26.666666666666668|             167.0|1.6666666666666667|0.6666666666666666|                0.675|               2.5|
|       Aaron Brooks|  2006|       85|             110|          192|            1105.0|               3|               8.0|            10.625|             13.75|              24.0|           138.125|             0.375|               1.0|   0.5729166666666666|             0.375|
|        Brett Favre|  2006|      147|             343|          613|            3885.0|              18|              18.0|            9.1875|           21.4375|           38.3125|          242.8125|             1.125|             1.125|   0.5595432300163132|               1.0|
|         Drew Brees|  2007|      149|             443|          655|            4428.0|              28|              18.0|            9.3125|           27.6875|           40.9375|            276.75|              1.75|             1.125|   0.6763358778625954|1.5555555555555556|
|   Bruce Gradkowski|  2006|      114|             177|          328|            1661.0|               9|               9.0|  8.76923076923077|13.615384615384615| 25.23076923076923|127.76923076923077|0.6923076923076923|0.6923076923076923|   0.5396341463414634|               1.0|
|    Matt Hasselbeck|  2005|      145|             294|          450|            3455.0|              24|              10.0|            9.0625|            18.375|            28.125|          215.9375|               1.5|             0.625|   0.6533333333333333|               2.4|
|       Tommy Maddox|  2005|       27|              34|           71|             406.0|               2|               4.0|               9.0|11.333333333333334|23.666666666666668|135.33333333333334|0.6666666666666666|1.3333333333333333|   0.4788732394366197|               0.5|
|      Jake Delhomme|  2007|        6|              55|           86|             617.0|               8|               1.0|               2.0|18.333333333333332|28.666666666666668|205.66666666666666|2.6666666666666665|0.3333333333333333|   0.6395348837209303|               8.0|
|       Mark Brunell|  2005|      150|             262|          454|            3050.0|              23|              10.0|             9.375|            16.375|            28.375|           190.625|            1.4375|             0.625|   0.5770925110132159|               2.3|
|        Marc Bulger|  2007|      106|             221|          378|            2392.0|              11|              15.0| 8.833333333333334|18.416666666666668|              31.5|199.33333333333334|0.9166666666666666|              1.25|   0.5846560846560847|0.7333333333333333|
|      David Garrard|  2007|      105|             208|          325|            2509.0|              18|               3.0|              8.75|17.333333333333332|27.083333333333332|209.08333333333334|               1.5|              0.25|                 0.64|               6.0|
|        Kurt Warner|  2005|       90|             242|          375|            2713.0|              11|               9.0|               9.0|              24.2|              37.5|             271.3|               1.1|               0.9|   0.6453333333333333|1.2222222222222223|
|      Kelly Holcomb|  2007|       15|              42|           83|             511.0|               2|               1.0|               5.0|              14.0|27.666666666666668|170.33333333333334|0.6666666666666666|0.3333333333333333|   0.5060240963855421|               2.0|
+-------------------+------+---------+----------------+-------------+------------------+----------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+---------------------+------------------+
only showing top 20 rows

Now, let's take a look at our top 40 seasons by **Completion Percentage**: \
*a redemption for 2019 Matt Schaub*

In [122]:
sql_qbsummary.sort("completion_percentage", ascending = False).show(40)

+-------------------+------+---------+----------------+-------------+------------------+----------------+------------------+------------------+------------------+------------------+------------------+-------------------+-------------------+---------------------+------------------+
|player_display_name|season|sum(week)|sum(completions)|sum(attempts)|sum(passing_yards)|sum(passing_tds)|sum(interceptions)|         avg(week)|  avg(completions)|     avg(attempts)|avg(passing_yards)|   avg(passing_tds)| avg(interceptions)|completion_percentage|      td_int_ratio|
+-------------------+------+---------+----------------+-------------+------------------+----------------+------------------+------------------+------------------+------------------+------------------+-------------------+-------------------+---------------------+------------------+
|      C.J. Beathard|  2023|       65|              40|           53|             349.0|               1|               0.0|10.833333333333334| 6.666666666666667| 8.833333333333334|58.166666666666664|0.16666666666666666|                0.0|   0.7547169811320755|              NULL|
|         Colt McCoy|  2021|       62|              74|           99|             740.0|               3|               1.0| 8.857142857142858|10.571428571428571|14.142857142857142|105.71428571428571|0.42857142857142855|0.14285714285714285|   0.7474747474747475|               3.0|
|        Matt Schaub|  2019|       52|              50|           67|             580.0|               3|               1.0|              10.4|              10.0|              13.4|             116.0|                0.6|                0.2|    0.746268656716418|               3.0|
|         Drew Brees|  2018|      130|             364|          489|            3992.0|              32|               5.0| 8.666666666666666|24.266666666666666|              32.6| 266.1333333333333| 2.1333333333333333| 0.3333333333333333|   0.7443762781186094|               6.4|
|         Drew Brees|  2019|      119|             281|          378|            2979.0|              27|               4.0|10.818181818181818|25.545454545454547| 34.36363636363637| 270.8181818181818| 2.4545454545454546|0.36363636363636365|   0.7433862433862434|              6.75|
|      Mason Rudolph|  2023|       66|              55|           74|             719.0|               3|               0.0|              16.5|             13.75|              18.5|            179.75|               0.75|                0.0|   0.7432432432432432|              NULL|
|        Taysom Hill|  2020|      147|              88|          121|             928.0|               4|               2.0|            9.1875|               5.5|            7.5625|              58.0|               0.25|              0.125|   0.7272727272727273|               2.0|
|         Nick Foles|  2018|       51|             141|          195|            1413.0|               7|               4.0|              10.2|              28.2|              39.0|             282.6|                1.4|                0.8|   0.7230769230769231|              1.75|
|         Drew Brees|  2017|      148|             386|          536|            4334.0|              23|               8.0|              9.25|            24.125|              33.5|           270.875|             1.4375|                0.5|   0.7201492537313433|             2.875|
|       Sam Bradford|  2016|      146|             395|          552|            3877.0|              20|               5.0| 9.733333333333333|26.333333333333332|              36.8|258.46666666666664| 1.3333333333333333| 0.3333333333333333|   0.7155797101449275|               4.0|
|         Drew Brees|  2011|      142|             471|          660|            5535.0|              46|              14.0|             8.875|           29.4375|             41.25|          345.9375|              2.875|              0.875|   0.7136363636363636|3.2857142857142856|
|         Colt McCoy|  2014|       57|              91|          128|            1057.0|               4|               3.0|              11.4|              18.2|              25.6|             211.4|                0.8|                0.6|            0.7109375|1.3333333333333333|
|      Aaron Rodgers|  2020|      148|             372|          526|            4299.0|              48|               5.0|              9.25|             23.25|            32.875|          268.6875|                3.0|             0.3125|   0.7072243346007605|               9.6|
|       Bailey Zappe|  2022|       22|              65|           92|             781.0|               5|               3.0|               5.5|             16.25|              23.0|            195.25|               1.25|               0.75|   0.7065217391304348|1.6666666666666667|
|         Drew Brees|  2009|      131|             363|          514|            4388.0|              34|              11.0| 8.733333333333333|              24.2|34.266666666666666|292.53333333333336| 2.2666666666666666| 0.7333333333333333|   0.7062256809338522| 3.090909090909091|
|         Drew Brees|  2020|       97|             275|          390|            2942.0|              24|               6.0| 8.083333333333334|22.916666666666668|              32.5|245.16666666666666|                2.0|                0.5|   0.7051282051282052|               4.0|
|         Joe Burrow|  2021|      143|             366|          520|            4611.0|              34|              14.0|            8.9375|            22.875|              32.5|          288.1875|              2.125|              0.875|   0.7038461538461539|2.4285714285714284|
|         Derek Carr|  2019|      147|             361|          513|            4054.0|              21|               8.0|            9.1875|           22.5625|           32.0625|           253.375|             1.3125|                0.5|   0.7037037037037037|             2.625|
|      Jake Browning|  2023|      117|             171|          243|            1936.0|              12|               7.0|              13.0|              19.0|              27.0|215.11111111111111| 1.3333333333333333| 0.7777777777777778|   0.7037037037037037|1.7142857142857142|
|       Chase Daniel|  2019|       20|              45|           64|             435.0|               3|               2.0| 6.666666666666667|              15.0|21.333333333333332|             145.0|                1.0| 0.6666666666666666|             0.703125|               1.5|
|     Ryan Tannehill|  2019|      128|             201|          286|            2742.0|              22|               6.0|10.666666666666666|             16.75|23.833333333333332|             228.5| 1.8333333333333333|                0.5|   0.7027972027972028|3.6666666666666665|
|     Deshaun Watson|  2020|      145|             382|          544|            4823.0|              33|               7.0|            9.0625|            23.875|              34.0|          301.4375|             2.0625|             0.4375|   0.7022058823529411| 4.714285714285714|
|         Alex Smith|  2012|       63|             153|          218|            1737.0|              13|               5.0|               6.3|              15.3|              21.8|             173.7|                1.3|                0.5|   0.7018348623853211|               2.6|
|       Kirk Cousins|  2018|      143|             425|          606|            4298.0|              30|              10.0|            8.9375|           26.5625|            37.875|           268.625|              1.875|              0.625|   0.7013201320132013|               3.0|
|       Jamie Martin|  2005|       92|             124|          177|            1277.0|               5|               7.0|              11.5|              15.5|            22.125|           159.625|              0.625|              0.875|   0.7005649717514124|0.7142857142857143|
|         Drew Brees|  2016|      148|             471|          673|            5208.0|              37|              15.0|              9.25|           29.4375|           42.0625|             325.5|             2.3125|             0.9375|   0.6998514115898959| 2.466666666666667|
|          Tony Romo|  2014|      133|             304|          435|            3705.0|              34|               9.0| 8.866666666666667|20.266666666666666|              29.0|             247.0| 2.2666666666666666|                0.6|   0.6988505747126437|3.7777777777777777|
|          Matt Ryan|  2016|      142|             373|          534|            4944.0|              38|               7.0|             8.875|           23.3125|            33.375|             309.0|              2.375|             0.4375|   0.6985018726591761| 5.428571428571429|
|       Kirk Cousins|  2015|      145|             379|          543|            4166.0|              29|              11.0|            9.0625|           23.6875|           33.9375|           260.375|             1.8125|             0.6875|   0.6979742173112339|2.6363636363636362|
|         Geno Smith|  2022|      160|             399|          572|            4282.0|              30|              11.0| 9.411764705882353|23.470588235294116| 33.64705882352941|251.88235294117646| 1.7647058823529411| 0.6470588235294118|   0.6975524475524476| 2.727272727272727|
|       Chase Daniel|  2018|       38|              53|           76|             515.0|               3|               2.0|               9.5|             13.25|              19.0|            128.75|               0.75|                0.5|   0.6973684210526315|               1.5|
|       Carson Wentz|  2018|       93|             279|          401|            3074.0|              21|               7.0| 8.454545454545455|25.363636363636363| 36.45454545454545|279.45454545454544| 1.9090909090909092| 0.6363636363636364|   0.6957605985037406|               3.0|
|       Dak Prescott|  2023|      164|             410|          590|            4516.0|              36|               9.0| 9.647058823529411| 24.11764705882353|34.705882352941174| 265.6470588235294| 2.1176470588235294| 0.5294117647058824|   0.6949152542372882|               4.0|
|      Philip Rivers|  2013|      145|             378|          544|            4478.0|              32|              11.0|            9.0625|            23.625|              34.0|           279.875|                2.0|             0.6875|   0.6948529411764706| 2.909090909090909|
|          Tony Romo|  2010|       24|             148|          213|            1605.0|              11|               7.0|               4.0|24.666666666666668|              35.5|             267.5| 1.8333333333333333| 1.1666666666666667|   0.6948356807511737|1.5714285714285714|
|       Kirk Cousins|  2023|       36|             216|          311|            2331.0|              18|               5.0|               4.5|              27.0|            38.875|           291.375|               2.25|              0.625|   0.6945337620578779|               3.6|
|          Matt Ryan|  2018|      145|             422|          608|            4924.0|              35|               7.0|            9.0625|            26.375|              38.0|            307.75|             2.1875|             0.4375|    0.694078947368421|               5.0|
|        Brock Purdy|  2023|      144|             308|          444|            4280.0|              31|              11.0|               9.0|             19.25|             27.75|             267.5|             1.9375|             0.6875|   0.6936936936936937|2.8181818181818183|
|          Jim Sorgi|  2005|       57|              43|           62|             444.0|               3|               1.0|              11.4|               8.6|              12.4|              88.8|                0.6|                0.2|   0.6935483870967742|               3.0|
|     Brandon Weeden|  2015|       45|              97|          140|            1043.0|               5|               2.0|               7.5|16.166666666666668|23.333333333333332|173.83333333333334| 0.8333333333333334| 0.3333333333333333|   0.6928571428571428|               2.5|
+-------------------+------+---------+----------------+-------------+------------------+----------------+------------------+------------------+------------------+------------------+------------------+-------------------+-------------------+---------------------+------------------+
only showing top 40 rows

Same thing here but with TD_int_ratio. \
Note that our `NULL` values aren't considered "higher" than our regular numeric values, and thus are omitted from the top of the list. \
Using a different approach to sorting, we can make sure those QBs who didn't throw an interception *all season* are rewarded for their achievement

In [131]:
sql_qbsummary.sort("td_int_ratio", ascending = False).show(5)

+-------------------+------+---------+----------------+-------------+------------------+----------------+------------------+------------------+------------------+------------------+------------------+------------------+-------------------+---------------------+------------+
|player_display_name|season|sum(week)|sum(completions)|sum(attempts)|sum(passing_yards)|sum(passing_tds)|sum(interceptions)|         avg(week)|  avg(completions)|     avg(attempts)|avg(passing_yards)|  avg(passing_tds)| avg(interceptions)|completion_percentage|td_int_ratio|
+-------------------+------+---------+----------------+-------------+------------------+----------------+------------------+------------------+------------------+------------------+------------------+------------------+-------------------+---------------------+------------+
|          Tom Brady|  2016|      134|             291|          432|            3554.0|              28|               2.0|11.166666666666666|             24.25|              36.0| 296.1666666666667|2.3333333333333335|0.16666666666666666|   0.6736111111111112|        14.0|
|         Nick Foles|  2013|      129|             203|          317|            2891.0|              27|               2.0| 9.923076923076923|15.615384615384615|24.384615384615383| 222.3846153846154| 2.076923076923077|0.15384615384615385|   0.6403785488958991|        13.5|
|        Josh McCown|  2013|       92|             149|          224|            1829.0|              13|               1.0|              11.5|            18.625|              28.0|           228.625|             1.625|              0.125|   0.6651785714285714|        13.0|
|      Aaron Rodgers|  2018|      146|             372|          597|            4442.0|              25|               2.0|             9.125|             23.25|           37.3125|           277.625|            1.5625|              0.125|   0.6231155778894473|        12.5|
|        Damon Huard|  2006|       69|             148|          244|            1878.0|              11|               1.0|               6.9|              14.8|              24.4|             187.8|               1.1|                0.1|   0.6065573770491803|        11.0|
+-------------------+------+---------+----------------+-------------+------------------+----------------+------------------+------------------+------------------+------------------+------------------+------------------+-------------------+---------------------+------------+
only showing top 5 rows

`.desc_nulls_first()` specifies a descending list, with `NULL` values listed first.

In [130]:
sql_qbsummary.sort(F.col("td_int_ratio").desc_nulls_first()).show(40)

+-------------------+------+---------+----------------+-------------+------------------+----------------+------------------+------------------+------------------+------------------+------------------+-------------------+-------------------+---------------------+-----------------+
|player_display_name|season|sum(week)|sum(completions)|sum(attempts)|sum(passing_yards)|sum(passing_tds)|sum(interceptions)|         avg(week)|  avg(completions)|     avg(attempts)|avg(passing_yards)|   avg(passing_tds)| avg(interceptions)|completion_percentage|     td_int_ratio|
+-------------------+------+---------+----------------+-------------+------------------+----------------+------------------+------------------+------------------+------------------+------------------+-------------------+-------------------+---------------------+-----------------+
|      Kerry Collins|  2007|       48|              50|           82|             531.0|               0|               0.0|               8.0| 8.333333333333334|13.666666666666666|              88.5|                0.0|                0.0|   0.6097560975609756|             NULL|
|      Charlie Batch|  2006|       71|              30|           52|             477.0|               5|               0.0|10.142857142857142| 4.285714285714286| 7.428571428571429| 68.14285714285714| 0.7142857142857143|                0.0|   0.5769230769230769|             NULL|
|        Matt Schaub|  2005|       65|              33|           64|             495.0|               4|               0.0| 9.285714285714286| 4.714285714285714| 9.142857142857142| 70.71428571428571| 0.5714285714285714|                0.0|             0.515625|             NULL|
|       Todd Collins|  2007|       62|              67|          105|             888.0|               5|               0.0|              15.5|             16.75|             26.25|             222.0|               1.25|                0.0|    0.638095238095238|             NULL|
|         Troy Smith|  2007|       62|              40|           76|             452.0|               2|               0.0|              15.5|              10.0|              19.0|             113.0|                0.5|                0.0|   0.5263157894736842|             NULL|
|        Jake Locker|  2011|       51|              34|           66|             542.0|               4|               0.0|              10.2|               6.8|              13.2|             108.4|                0.8|                0.0|   0.5151515151515151|             NULL|
|    Jacoby Brissett|  2016|        9|              34|           55|             400.0|               0|               0.0|               3.0|11.333333333333334|18.333333333333332|133.33333333333334|                0.0|                0.0|   0.6181818181818182|             NULL|
|    Jimmy Garoppolo|  2016|       49|              43|           63|             502.0|               4|               0.0| 8.166666666666666| 7.166666666666667|              10.5| 83.66666666666667| 0.6666666666666666|                0.0|   0.6825396825396826|             NULL|
|        Brian Hoyer|  2016|       27|             134|          200|            1445.0|               6|               0.0|               4.5|22.333333333333332|33.333333333333336|240.83333333333334|                1.0|                0.0|                 0.67|             NULL|
|         Nick Foles|  2016|       17|              36|           55|             410.0|               3|               0.0|               8.5|              18.0|              27.5|             205.0|                1.5|                0.0|   0.6545454545454545|             NULL|
|     Derek Anderson|  2014|       30|              65|           97|             701.0|               5|               0.0|               6.0|              13.0|              19.4|             140.2|                1.0|                0.0|   0.6701030927835051|             NULL|
|         Tom Savage|  2016|       48|              46|           73|             461.0|               0|               0.0|              16.0|15.333333333333334|24.333333333333332|153.66666666666666|                0.0|                0.0|   0.6301369863013698|             NULL|
|         Matt Moore|  2019|       54|              59|           91|             659.0|               4|               0.0|               9.0| 9.833333333333334|15.166666666666666|109.83333333333333| 0.6666666666666666|                0.0|   0.6483516483516484|             NULL|
|      C.J. Beathard|  2020|       67|              66|          104|             787.0|               6|               0.0|11.166666666666666|              11.0|17.333333333333332|131.16666666666666|                1.0|                0.0|   0.6346153846153846|             NULL|
|        Andy Dalton|  2023|        8|              34|           58|             361.0|               2|               0.0|               4.0|              17.0|              29.0|             180.5|                1.0|                0.0|   0.5862068965517241|             NULL|
|      Mason Rudolph|  2023|       66|              55|           74|             719.0|               3|               0.0|              16.5|             13.75|              18.5|            179.75|               0.75|                0.0|   0.7432432432432432|             NULL|
|     Desmond Ridder|  2022|       66|              73|          115|             708.0|               2|               0.0|              16.5|             18.25|             28.75|             177.0|                0.5|                0.0|   0.6347826086956522|             NULL|
|      C.J. Beathard|  2023|       65|              40|           53|             349.0|               1|               0.0|10.833333333333334| 6.666666666666667| 8.833333333333334|58.166666666666664|0.16666666666666666|                0.0|   0.7547169811320755|             NULL|
|          Tom Brady|  2016|      134|             291|          432|            3554.0|              28|               2.0|11.166666666666666|             24.25|              36.0| 296.1666666666667| 2.3333333333333335|0.16666666666666666|   0.6736111111111112|             14.0|
|         Nick Foles|  2013|      129|             203|          317|            2891.0|              27|               2.0| 9.923076923076923|15.615384615384615|24.384615384615383| 222.3846153846154|  2.076923076923077|0.15384615384615385|   0.6403785488958991|             13.5|
|        Josh McCown|  2013|       92|             149|          224|            1829.0|              13|               1.0|              11.5|            18.625|              28.0|           228.625|              1.625|              0.125|   0.6651785714285714|             13.0|
|      Aaron Rodgers|  2018|      146|             372|          597|            4442.0|              25|               2.0|             9.125|             23.25|           37.3125|           277.625|             1.5625|              0.125|   0.6231155778894473|             12.5|
|        Damon Huard|  2006|       69|             148|          244|            1878.0|              11|               1.0|               6.9|              14.8|              24.4|             187.8|                1.1|                0.1|   0.6065573770491803|             11.0|
|      Aaron Rodgers|  2020|      148|             372|          526|            4299.0|              48|               5.0|              9.25|             23.25|            32.875|          268.6875|                3.0|             0.3125|   0.7072243346007605|              9.6|
|      Aaron Rodgers|  2021|      149|             366|          531|            4115.0|              37|               4.0|            9.3125|            22.875|           33.1875|          257.1875|             2.3125|               0.25|   0.6892655367231638|             9.25|
|          Tom Brady|  2010|      148|             324|          492|            3900.0|              36|               4.0|              9.25|             20.25|             30.75|            243.75|               2.25|               0.25|   0.6585365853658537|              9.0|
|      Jake Delhomme|  2007|        6|              55|           86|             617.0|               8|               1.0|               2.0|18.333333333333332|28.666666666666668|205.66666666666666| 2.6666666666666665| 0.3333333333333333|   0.6395348837209303|              8.0|
|      Aaron Rodgers|  2014|      144|             341|          520|            4381.0|              38|               5.0|               9.0|           21.3125|              32.5|          273.8125|              2.375|             0.3125|   0.6557692307692308|              7.6|
|      Aaron Rodgers|  2011|      128|             342|          501|            4636.0|              45|               6.0| 8.533333333333333|              22.8|              33.4|309.06666666666666|                3.0|                0.4|   0.6826347305389222|              7.5|
|         Drew Brees|  2019|      119|             281|          378|            2979.0|              27|               4.0|10.818181818181818|25.545454545454547| 34.36363636363637| 270.8181818181818| 2.4545454545454546|0.36363636363636365|   0.7433862433862434|             6.75|
|      Aaron Rodgers|  2019|      142|             353|          569|            4002.0|              26|               4.0|             8.875|           22.0625|           35.5625|           250.125|              1.625|               0.25|   0.6203866432337434|              6.5|
|         Drew Brees|  2018|      130|             364|          489|            3992.0|              32|               5.0| 8.666666666666666|24.266666666666666|              32.6| 266.1333333333333| 2.1333333333333333| 0.3333333333333333|   0.7443762781186094|              6.4|
|    Patrick Mahomes|  2020|      126|             390|          588|            4740.0|              38|               6.0|               8.4|              26.0|              39.2|             316.0|  2.533333333333333|                0.4|   0.6632653061224489|6.333333333333333|
|          Tom Brady|  2007|      143|             398|          578|            4806.0|              50|               8.0|            8.9375|            24.875|            36.125|           300.375|              3.125|                0.5|   0.6885813148788927|             6.25|
|     Russell Wilson|  2019|      142|             341|          516|            4110.0|              31|               5.0|             8.875|           21.3125|             32.25|           256.875|             1.9375|             0.3125|   0.6608527131782945|              6.2|
|      David Garrard|  2007|      105|             208|          325|            2509.0|              18|               3.0|              8.75|17.333333333333332|27.083333333333332|209.08333333333334|                1.5|               0.25|                 0.64|              6.0|
|   Matthew Stafford|  2010|       26|              57|           96|             535.0|               6|               1.0|               6.5|             14.25|              24.0|            133.75|                1.5|               0.25|              0.59375|              6.0|
|      Lamar Jackson|  2019|      128|             265|          401|            3127.0|              36|               6.0| 8.533333333333333|17.666666666666668|26.733333333333334|208.46666666666667|                2.4|                0.4|   0.6608478802992519|              6.0|
|       Dak Prescott|  2016|      146|             311|          459|            3667.0|              23|               4.0|             9.125|           19.4375|           28.6875|          229.1875|             1.4375|               0.25|   0.6775599128540305|             5.75|
|      Aaron Rodgers|  2016|      149|             401|          610|            4428.0|              40|               7.0|            9.3125|           25.0625|            38.125|            276.75|                2.5|             0.4375|   0.6573770491803279|5.714285714285714|
+-------------------+------+---------+----------------+-------------+------------------+----------------+------------------+------------------+------------------+------------------+------------------+-------------------+-------------------+---------------------+-----------------+
only showing top 40 rows